### ISSUE TITLE
Hide values of the mysterious densities and gravity 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#10]
In the actual development, the mystery densities (in the explore, shapes, and applications screen) and gravity (in the explore screen) values are displayed in the readout:
![image](https://user-images.githubusercontent.com/26031501/115943972-acf99280-a478-11eb-8f2f-f93eb12e1ae1.png)

It needs to be changed to have the same behavior that the masses and springs sim. 

![image](https://user-images.githubusercontent.com/26031501/115943998-e6320280-a478-11eb-8ed5-6d30f2c8cc42.png)

When the user selects the mystery option, the slider and readout disappear, and in place, an invitation for the student to calculate the value appears: 
![image](https://user-images.githubusercontent.com/26031501/115943994-d87c7d00-a478-11eb-9ec0-40a30f3d26ae.png)

In Buoyanci the strings should be:

What is the value of the fluid density?  and What is the value of gravity?

**Comment by jonathanolson** [comment]
Implemented, can you try it out?

**Comment by DianaTavares** [comment]
working!!
