### ISSUE TITLE
Changing the boat's geometry for a simpler initial water level

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#100]
Why? Because this can facilitate students' productions and calculations on the boat screen. 
Worries? having at some point more water than the limit that the pool can contain.

During Feb/12/24 meeting MK commented that will think about this idea.

**Comment by DianaTavares** [comment]
Also, KP suggestion during that meeting was to modify the boat material or its walls to make that the initial state of the screen show better numbers, (for example 103 L). I love more the idea of the setup button to 100L, but if it is getting hard, KP solution is  good for to have at least one easy to calculate/predict/compare scenario.

**Comment by AgustinVallejo** [comment]
Changing the title on this issue to work on boat's geometry. We think the "Set to 100L" button is not desirable.

**Comment by AgustinVallejo** [comment]
Now the initial boat geometry displaces exactly 3L of water. Please double check and close if ready

**Comment by DianaTavares** [comment]
It works!!
