### ISSUE TITLE
Factor out the mass input listener from the screen view

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#104]
From https://github.com/phetsims/buoyancy/issues/78, adding mass drag sounds directly in the screen view helped see the break in modularity.

**Comment by samreid** [comment]
I factored out BackgroundEventTargetListener and it seems to be working in my testing. I noted several TODOs that would be good to check in about. Feel free to finish it up.

**Comment by zepumph** [comment]
I looked at things, and decided to "go all in" with two main changes:
1. Provided only specific items of screen view (which allowed us to get rid of the parametric type).
2. Use the constructor, and more instance fields to implement TInputListener.

Feel free to close.

**Comment by samreid** [comment]
Looks good, thanks. Closing.
