### ISSUE TITLE
Delete from the bottle material list: Lead and Mercury

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#106]
Leave the list of materials to Copper:
![image](https://github.com/phetsims/buoyancy/assets/26031501/e3942811-6219-45e6-a593-e7511bda0c48)

In that way, the max value of the mass slider is 90 kg, and allows better visibility for less dense materials:
![image](https://github.com/phetsims/buoyancy/assets/26031501/9b9dcbb9-3061-4f4d-bacd-3c863cf63119)

**Comment by AgustinVallejo** [comment]
Closing as completed

**Comment by DianaTavares** [comment]
I am reopening because the range of the mass slider is not 90 kg (check my first comment):

![image](https://github.com/phetsims/buoyancy/assets/26031501/20727734-a2b3-428c-b8da-efd0dabc31d2)

**Comment by zepumph** [comment]
[DELETED]

UPDATE: Oops, I miss understood. Let me take a look.

**Comment by zepumph** [comment]
Fixed above

**Comment by DianaTavares** [comment]
Sorry that I continue asking you for extra refinements, probably is better to open another issue? But Custom option is  strange. 

Looks strange for me that the max value of mass is 89.6 kg. I understand that is the max value for copper, but custom? Students always enjoy playing with the extremes of values, then I was thinking of a nicer number. In the begging I think in 100 kg, but that makes that a Custom block can have a density of 100 kg/L, that is just crazy! Then let's make custom the same that explore:

- [ ]  Make that the Custom mass range in **bottle** goes up to 27 kg.

I also checked that the Custom option in the boat screen only goes to 10 kg, and also need to go to 27.
![image](https://github.com/phetsims/buoyancy/assets/26031501/2db12144-1138-47cf-a3cb-cde1de497a57)

- [ ]  Make that the Custom mass range in **boat** goes up to 27 kg.

**Comment by zepumph** [comment]
The above has been sorted out over in https://github.com/phetsims/buoyancy/issues/115
