### ISSUE TITLE
Add info button to the shapes screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#107]
The position is displayed in the picture:
![image](https://github.com/phetsims/buoyancy/assets/26031501/49a5f701-86a4-4395-b2d8-34dd76e6b227)

and the text is: 

This simulation is limited to vertical forces, without considering torque. Object rotations and other more complex movements are not considered in the model. 

![image](https://github.com/phetsims/buoyancy/assets/26031501/bd08ea3f-2b86-41f4-9988-5516f3084130)

**Comment by zepumph** [comment]
Amazing. Thanks
