### ISSUE TITLE
Modify the mass range of the custom option in the block control

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#11]
Allow that the custom block mass control can have all the range of values (min = 0.5 to max=27). This control is only in the Explore screen. 

![image](https://user-images.githubusercontent.com/26031501/115944458-7f621880-a47b-11eb-8de4-99f20057920a.png)

**Comment by jonathanolson** [comment]
This control seems incredibly similar to the Intro screen in Density... is this specifically a request for just Buoyancy, and we want to leave the current behavior for Density? I'm a bit skeptical of that, since they seem to be serving similar purposes.

**Comment by DianaTavares** [comment]
The density learning goal was that students explore the relationship of mass, volume, and density, and how the density value can be used to identify if an object can float or not in water. A max density value of 10 kg/L was enough for that learning goal. 

This other simulation is about the buoyancy force,  how this force and weight come into play to determine whether an object floats or sinks, and if it sinks,  students can explore its apparent weight. Buoyancy doesn't have only water, it has denser fluids, where denser materials can float. Then this simulation needs to allow to have more denser materials, for example, something that can sink in mercury.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by DianaTavares** [comment]
Working! thanks!!
