### ISSUE TITLE
Add "PVC" to the list of materials 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#111]
To this list:
![image](https://github.com/phetsims/buoyancy/assets/26031501/c5ca3f93-5263-4f9c-ac0e-dbbdc52cf239)

On all the screens. It is also going to be included in Buoyancy:Basics, and it can affect Density. 

I found on the internet that PVC density changes with the addition of different additives, but is normally between 1.44 and 1.48 g/cm3. Then in the simulation we can use 1.44 kg/L.

**Comment by AgustinVallejo** [comment]
@DianaTavares please make sure this is as you desire

**Comment by DianaTavares** [comment]
It works well!! But don't like the color. All the other materials in to explore look like the material (ice, etc), When I look for a block (and box) of PVC, something like this appears:

![image](https://github.com/phetsims/buoyancy/assets/26031501/61cd46b1-1e74-4196-80ac-832271097293)
![image](https://github.com/phetsims/buoyancy/assets/26031501/f72bc4be-a243-4944-93fb-b9a7c4e580e6)


then I suggest it white, and the shining effect that the blocks like wood have: 

![image](https://github.com/phetsims/buoyancy/assets/26031501/085951fa-1ac5-4c20-be7e-35ba63b6df30)

**Comment by DianaTavares** [comment]
I am going to close this issue and open a new one with all the color of the blocks that are a little strange for me.
