### ISSUE TITLE
New Screen: Lab

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#113]
This new screen goes between Explore and Shapes. 

**This is its initial state:**
![image](https://github.com/phetsims/buoyancy/assets/26031501/09dd591f-f952-414a-878d-76bcb4ba29dc)

**Fluid displaced**
When "Fluid displaced" is selected, a beaker panel will appear in the position shown in the next picture (between the forces panel and the ground:
![image](https://github.com/phetsims/buoyancy/assets/26031501/801d6596-a613-4220-8ef4-b9c82bacb9f4)

I want the panel to have the same color that the other panels, but the scale color needs to be darker. I couldn't do that in the mock-up, but I hope you can be in the code. 

The fluid pool volume is 100L, then the beaker will fill with fluid with the operation:  the value of fluid pool volume — 100L. The max volume of the breaker is 10L, and then it has tick marks every 1 L, with a bigger tick mark in 5 and 10L. The color of the fluid inside needs to match the fluid in the pool. 

**Sale in the fluid**
The scale can move only in the vertical direction with a control like a slider 
![image](https://github.com/phetsims/buoyancy/assets/26031501/89c32d1a-358f-4baa-b68a-f421a41cc3cb)

The movement goes from the bottom, to the surface (it can't go out of the pool or affect the Fluid displaced measurement) 
![image](https://github.com/phetsims/buoyancy/assets/26031501/7179191e-1f99-4818-a238-88c7a74f036b)

**% submerged panel**
When % submerged (#112 ) is active, the panel will be placed in the bottom of the density panel:
![image](https://github.com/phetsims/buoyancy/assets/26031501/bec7e339-d3ba-4983-bc92-0decec9410d4)
 

**Scale on the ground**
make it unmovable. We don't want that users move in the pool. 

**Icon**
This is the icon, but I hope that by drawing it with code looks much better! Use the same scale that the screens, only showing N (units). 

![image](https://github.com/phetsims/buoyancy/assets/26031501/fe257efd-e23a-47f4-8442-744457b2a560)

**Comment by zepumph** [comment]
Scaffolding committed. Right now it is a direct copy of Applications.

**Comment by zepumph** [comment]
- [x] Make sure custom range goes all the way to 27 for the block mass.

**Comment by zepumph** [comment]
- [x] Do we want the "A" label on the block? Probably not.
- [x] Do we want to support the mystery materials like in the explore screen?

**Comment by zepumph** [comment]
Lots of work still to do here, but I made a commit for the displaced fluid panel (currently invisible). I'll get back to things tomorrow.

**Comment by zepumph** [comment]
Good progress here today, but definitely not done here, but here is the current fluid displaced panel:

<img width="267" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/7c5e457b-bb21-46f4-a26a-54273f4fd6c8">


More to be done next week. (including 4 TODOs)

**Comment by zepumph** [comment]
Making progress:
![image](https://github.com/phetsims/buoyancy/assets/6856943/a081dcea-c944-447c-b393-60836eee131a)

**Comment by zepumph** [comment]
I finished the design of the fluid displaced panel, and created https://github.com/phetsims/buoyancy/issues/129 for @DianaTavares to look at. I'll continue on with other items here.

**Comment by zepumph** [comment]
Hey @DianaTavares! @samreid and I believe that this issue is ready for review. Almost everything has been implemented, and remaining work is over in side issues:

Sticky scale component (totally not working right now): https://github.com/phetsims/density-buoyancy-common/issues/107
Screen icon: https://github.com/phetsims/buoyancy/issues/48

Can you take a look at the screen and let me know if there is anything you'd like changed? The only main difference from the mockup is that there is no "A" label, since there isn't a "B" block to add in.

**Comment by DianaTavares** [comment]
It is amazing!! in the last design meeting, we agreed to change the "gravity control" to a new place, but I created an issue with those changes in #133 
![image](https://github.com/phetsims/buoyancy/assets/26031501/a5ef1582-4227-4c29-818d-264fdd06595a)

Then we can close this issue. Thanks!!
