### ISSUE TITLE
Turn on PhET-iO Validation

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#114]
Discovered when we were surprised that we didn't get an assertion from a duplicate phetioID over in https://github.com/phetsims/buoyancy/issues/31

**Comment by samreid** [comment]
@zepumph would you take a look and see if there is more to do in this issue?

**Comment by zepumph** [comment]
Mostly good but I have a few questions:

* Should there be a blank object in package.jsons for `phet-io`? I don't think so.
* This line is commented out in Mass.ts: [// phetioDynamicElement: true](https://github.com/phetsims/density-buoyancy-common/blob/f5586050caec5b7b83b96ee3e2b400161f34ff0f/js/common/model/Mass.ts#L262)

I didn't get through everything.

**Comment by samreid** [comment]
> Should there be a blank object in package.jsons for phet-io? I don't think so.

I don't think so either

> This line is commented out in Mass.ts: [// phetioDynamicElement: true](https://github.com/phetsims/density-buoyancy-common/blob/f5586050caec5b7b83b96ee3e2b400161f34ff0f/js/common/model/Mass.ts#L262)

Good catch, that was a crutch that got me pointed toward https://github.com/phetsims/density-buoyancy-common/blob/f5586050caec5b7b83b96ee3e2b400161f34ff0f/js/buoyancy/model/BuoyancyShapesModel.ts#L99-L105 and it can be removed.

I think we should try to make the density, buoyancy and buoyancy-basics package.jsons look as similar as possible. Right now they have deviations, even different lint rules.

**Comment by zepumph** [comment]
Ok great. I made some good changes to the packages for consistency. Mostly getting lint consistent. I also threw in testing designed changes for all three in phet-io. Seems just as good to do it for all sims.

**Comment by zepumph** [comment]
Ready to close?
