### ISSUE TITLE
Color of some blocks' materials

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#116]
I am not sure if this can be improved but, the list of the “original” materials of the simulations (the ones in Density) looks like the real colors/textures materials, (like brick, ice, etc). The new materials, in some cases, are just colored blocks. I remember in  previous Jonathan experiments with this simulations, that he created blocks of metals that look like shinning, that effect can work for some material in the list. The ones that I will can be improved are:

**PVC**
It is a gray block:
![image](https://github.com/phetsims/buoyancy/assets/26031501/21d26094-26e9-42ff-b398-be3d48a743df)

I associate it more with a white color. It is possible to have the effect of a 3D-printed block? 
 
![311349148-f72bc4be-a243-4944-93fb-b9a7c4e580e6](https://github.com/phetsims/buoyancy/assets/26031501/a687da07-eed0-499e-8390-42286cddb8d2)

**Pyrite and Gold**
Now it is a kind of orange block:
![image](https://github.com/phetsims/buoyancy/assets/26031501/3a75d88c-7e5a-4a73-9c2c-4c3d656beb18)

I think that something more "mirror" and shinning effect, yellow block 
![image](https://github.com/phetsims/buoyancy/assets/26031501/8285f8bf-2cd2-4d80-96f2-99bce9d9c71d)
![image](https://github.com/phetsims/buoyancy/assets/26031501/4c4e8674-f4c9-4e8d-a593-fed4bf1db314)

**Silver**
In the simulation, silver is the same color that gold:
![image](https://github.com/phetsims/buoyancy/assets/26031501/a5a553c1-41b3-41cf-9ad8-20495a1d6d04)

At least something gray:
![image](https://github.com/phetsims/buoyancy/assets/26031501/55896f32-b7b8-4c7f-94f3-3e2ded5209fc)
![image](https://github.com/phetsims/buoyancy/assets/26031501/e8363b1e-c772-4c51-ab8b-5a2701efb88d)

**Tantalum** 
Also, the same color that gold in the simulation. I am thinking in the same that Aluminum but darker:

![image](https://github.com/phetsims/buoyancy/assets/26031501/369969e9-3b98-4385-9539-d0ad7d1403bc)

Or like silver, but less shining:
![image](https://github.com/phetsims/buoyancy/assets/26031501/61b9a839-c1a0-4527-a295-a9f258e5495b)

**Platinum**
Looks like it should be like silver, bur wither. 
![image](https://github.com/phetsims/buoyancy/assets/26031501/5766b5f2-9228-474f-8719-2b34bd06c801)

**Comment by zepumph** [comment]
@AgustinVallejo will take the lead on this, and will look at https://ambientcg.com/ (where other textures came from as documented in https://github.com/phetsims/density-buoyancy-common/blob/843a0377d3423df92dd070f875f0a6e8dcf4c4cc/images/license.json#L30. Thanks!

**Comment by AgustinVallejo** [comment]
Reminder to also do some work on Mystery Materials:
- [x] Lab:
Material O - color: red 
Material P color- green
- [x] Applications Boat
Material V - Color yellow
Material W - color blue

**Comment by AgustinVallejo** [comment]
This is ready to review, let me know if this is what you wanted @DianaTavares

**Comment by AgustinVallejo** [comment]
Just noticed I missed the PVC, please review the rest while I implement that.

**Comment by DianaTavares** [comment]
I only have one observation:
 The custom material now looks strange. With a small density (considering that its density range is from 0.1 to 27 kg), it is already black (look at the picture). Density also has a full black block with a small density (3.1 kk/L), but the range goes to 10 kg/L. I feel that the gray-black gradient needs to be bigger here. 

![image](https://github.com/phetsims/buoyancy/assets/26031501/4e43bea3-f2ea-4507-b599-efa20c400b75)

**Comment by AgustinVallejo** [comment]
Addressing last Diana's comment in https://github.com/phetsims/buoyancy/issues/128 since that's not consequence of the changes done here. Closing this one as completed.
