### ISSUE TITLE
Modify the angle view and perspective of the sim

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#12]
In the actual simulation, the vectors don't look vertical when they are compared with the edges of the pool and blocks
![image](https://user-images.githubusercontent.com/26031501/116621621-165e2300-a909-11eb-9578-0db71fa0a2dc.png)

This effect decreases close to the center of the simulation. 
![image](https://user-images.githubusercontent.com/26031501/116622078-b916a180-a909-11eb-9144-252f9fc213b1.png)

the suggestion is to play with the angle of vision and perspective to improve the visualization of the vectors, to look verticals compares with the rest of the objects in the simulation.

**Comment by jonathanolson** [comment]
Continuing to render these in scenery, BUT still properly compensating for the projection (i.e. shearing them) sounds like the best approach here. Should be able to get an affine matrix for that given vertical line.

**Comment by jonathanolson** [comment]
![image](https://user-images.githubusercontent.com/480878/127215085-22ae7697-2614-48a9-8e82-e0915d852a66.png)

Implemented above, can you try it out and see how it works?

**Comment by DianaTavares** [comment]
This is already fixed in master with the new values related to the angle of view:

![image](https://user-images.githubusercontent.com/26031501/130504513-8e8f622a-c8e7-4335-8ba6-66185c01f88f.png)
