### ISSUE TITLE
Changes in the Material control in the Bottle-Applications screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#120]
With this control is not possible to have a custom material with a specific density, and fill the bottle with it. 
![image](https://github.com/phetsims/buoyancy/assets/26031501/45b78f66-5fcc-4bc6-a2a0-93f77c16f402)

Proposal:
For known materials:
![image](https://github.com/phetsims/buoyancy/assets/26031501/0506a8ea-9551-449f-b3fc-00454c8d0bb0)

For custom:
![image](https://github.com/phetsims/buoyancy/assets/26031501/1ddc7f1b-beb7-45b7-831c-4597be001020)

Where the density goes from 0.05 kg/L to 20 kg/L

For mystery:
![image](https://github.com/phetsims/buoyancy/assets/26031501/0d20f982-82cc-4da9-8a76-d3c13c519a1f)

Material R: Ice (0.92 kg/L)
Material S: Lead (11.34 kg/L)

**Comment by zepumph** [comment]
- [x] Separate per scene (already done?)
- [x] Mass is a readout instead of controllable (still changes based on volume)
- [x] Custom material adds a density control
- [x] Add two mystery materials R and S
- [x] Decide on colors for above mystery materials
- [x] Mystery materials cause mass readout to be `?`
- [ ] ~In this picture, we have a min volume for custom. I don't believe we will need this once the volume doesn't change the density.~
    <img width="364" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/198ea0c0-13d5-494c-bd1e-7d0a85eaebbd">
- [ ] ~The empty bottle defaults to 100g. @kathy-phet and I like decreasing that a bit.~

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
I believe a rough draft is in place now. The implementation is a bit rough (9 TODOs), but it would be a good time to check in with @DianaTavares. 

Please also note that we need colors for the new mystery materials (checkbox above).

**Comment by zepumph** [comment]
Ok. I think that a sync conversation would be best to continue here. There is some nuance about being able to set the min volume to 0 on the custom material. It may not be worth the cost. Let's talk tomorrow.

**Comment by DianaTavares** [comment]
We. can discuss this after the stand-up meeting tomorrow! 
Some ideas:

>  In this picture, we have a minvolume for custom. I don't believe we will need this once the volume doesn't change the density.

I agree! The min can be 0.

> The empty bottle defaults to 100g. @kathy-phet and I like decreasing that a bit.

I see the discussion in Slack. The volume of the shell of the bottle is 0 to be practical. for the same reason, the mass is 100g, because is an easy operation for the student to make the operations. I think this screen needs to have the bottle's mass label by default 

> Decide on colors for above mystery materials

I like the colors they have now! but less shining. I tried to play with the color editor, but I didn't find the colors for materials S and R. But I think that if you go to a darker gradian in the top, it will be ok! look how the copper is not so shinning: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/15463846-31c9-4c55-ac52-8416fe2e3e1d)
![image](https://github.com/phetsims/buoyancy/assets/26031501/0751ea28-cd65-4054-82a2-748b845236ab)

**Comment by DianaTavares** [comment]
Continue with the conversation related to colors, I decide the color for the second mystery material (R)

`(255, 115, 0, 0.61) `
Orange:
![image](https://github.com/phetsims/buoyancy/assets/26031501/82b3a353-68c5-444a-bfbc-674302bcf462)

Mystery Material S is good with the changes done in the meeting we had yesterday:
![image](https://github.com/phetsims/buoyancy/assets/26031501/37e1eb64-b682-4ce5-a01f-1b2fc31d97f2)


> In this picture, we have a minvolume for custom. I don't believe we will need this once the volume doesn't change the density.
In yesterday's meeting we also agreed that the volume can be the min that is already in the code (it is not zero, and @zepumph comments that change that can be challenging, and the truth is that we don't need it to be zero)

We also agree that this screen needs to:

- [x] have the mass label open on this screen by default

**Comment by zepumph** [comment]
I also have:

>The empty bottle defaults to 100g. @kathy-phet and I like decreasing that a bit.

Do we want this?

**Comment by DianaTavares** [comment]
No, let's leave it to 100g because is a more manageable number and evident that the bottle have mass by itself

**Comment by zepumph** [comment]
Alright. This is complete. Thanks all!
