### ISSUE TITLE
Mystery Materials 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#121]
We agreed in add them to Lab and Applications. These are the suggestions:

- [x] Lab:

Material O: Human (0.95 kg/L) - 5L - 4.75 kg - color: red 
Material P: Diamond (3.51 kg/L) - 5 L -15.44 kg, color- green

- [x] Applications Boat

Material V: Titanium (4.5 kg/L) - 6L - 27 kg - Color yellow
Material W: Mercury (13.59 kg/L) - 3L - 40.77kg - color blue

We already have this implementation in Explore, but with the mane "mystery":
![image](https://github.com/phetsims/buoyancy/assets/26031501/f95c96e9-c0bf-43d3-ad8c-e56dd293e715)

- [x] We need to change the title to “Material”

Why material and not mystery?
All the other mystery values in the simulation, we don't use the word mystery, in place we use something related to the variable: 

![image](https://github.com/phetsims/buoyancy/assets/26031501/95d52f02-0a02-4473-b75f-383a51988b46)

Bottle also need mystery materials, but that was described in the #120 issue.

**Comment by AgustinVallejo** [comment]
Regarding the Applications request, it seems to be a bit crowded. Right now the entire combo box doesn't even fit. It can be moved up but just wanted to check this is a direction we want to move towards. (The hidden last element is Custom) @DianaTavares 
![image](https://github.com/phetsims/buoyancy/assets/37052186/9a2241f4-f167-4611-b622-d6193dd3b88f)

**Comment by DianaTavares** [comment]
Yes please, try to move it up. Wow it is a big list!

**Comment by AgustinVallejo** [comment]
Almost done by the above commit. For some reason the panel in Applications Screen View is not automatically changing to the mystery message, will investigate tomorrow.

Looking like this now: 
![image](https://github.com/phetsims/buoyancy/assets/37052186/cb8bc224-5d87-4566-8187-ef28f240329e)

**Comment by AgustinVallejo** [comment]
Assigning to @DianaTavares to review this feature (except the colors which I'll work on https://github.com/phetsims/buoyancy/issues/116). Feel free to close if ready :)

**Comment by DianaTavares** [comment]
Perfecto! Thanks!
