### ISSUE TITLE
Updates to preference for percentageSubmergedVisible

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#126]
From https://github.com/phetsims/buoyancy/issues/112. We need to be able to toggle the default of this preference based on the sim running. In Buoyancy we want the preference to default off (not showing the panel), then in buoyancy basics we do want it by default. The query parameter should still override these defaults though, so we many need to outfit a null/true/false value so we know if the query parameter was provided. Another idea is to just use `QueryStringMachine.containsKey()` to know if the value was provided vs is the default.

**Comment by samreid** [comment]
I'll take a look at this. Self-assigning.

**Comment by samreid** [comment]
I recommend a solution like this:

<details>

```diff

Subject: [PATCH] Address TODOs, see https://github.com/phetsims/chipper/issues/1429
---
Index: js/common/DensityBuoyancyCommonQueryParameters.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/DensityBuoyancyCommonQueryParameters.ts b/js/common/DensityBuoyancyCommonQueryParameters.ts
--- a/js/common/DensityBuoyancyCommonQueryParameters.ts	(revision 0c8d369951cb271e2ae1464488db56a95af5f0c2)
+++ b/js/common/DensityBuoyancyCommonQueryParameters.ts	(date 1712764806826)
@@ -11,6 +11,8 @@
 export const VolumeUnitsValues = [ 'liters', 'decimetersCubed' ] as const;
 export type VolumeUnits = ( typeof VolumeUnitsValues )[number];
 
+const defaultPercentageSubmergedVisible = phet.joist.packageJSON.name !== 'buoyancy-basics';
+
 const DensityBuoyancyCommonQueryParameters = QueryStringMachine.getAll( {
 
   gEarth: {
@@ -31,7 +33,7 @@
   // Displays/hides the percentage submerged readout accordion box
   percentageSubmergedVisible: {
     type: 'boolean',
-    defaultValue: true,
+    defaultValue: defaultPercentageSubmergedVisible,
     public: true
   },
 

```

</details>

@zepumph does this look good? Feel free to commit or let me know if I should.

**Comment by zepumph** [comment]
@samreid and I got to a commit point. Using `packageJSON.name` was such a nicer way to handle this than anything I was going to recommend. We also cleaned up how the preference is managed, since it was added to `density` too. 


**@DianaTavares, the behavior is now as follows:**
* In Density, there is no notion of % submerged, (preference or panels)
* In Buoyancy, % submerged is supported, but defaults off.
* In Buoyancy Basics, % submerged is supported, but defaults on.

Please review and feel free to close.

**Comment by DianaTavares** [comment]
Thanks team!

The behavior is correct! But in Buoyancy basics, yes the panel is on in the preference menu, but 

- [ ] the panel needs to be closed by default. 

Like this: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/3ac96984-088c-4364-b2fb-91967b2e30f5)

Basics don't have the “compare” screen, but there also the % submerged panel is on, but close by default.

**Comment by zepumph** [comment]
Currently we don't actually have any code implemented for buoyancy basics. This is just an exact copy of the buoyancy explore screen. I wonder if we can add this to a list for when we implement the buoyancy basics sim.

**Comment by zepumph** [comment]
Wait. In Buoyancy, should the panel default to closed also?
