### ISSUE TITLE
Fix the gradient on the Custom material block

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/buoyancy#128]
@DianaTavares mentioned in https://github.com/phetsims/buoyancy/issues/116
> I only have one observation:
The custom material now looks strange. With a small density (considering that its density range is from 0.1 to 27 kg), it is already black (look at the picture). Density also has a full black block with a small density (3.1 kk/L), but the range goes to 10 kg/L. I feel that the gray-black gradient needs to be bigger here.

This is not a consequence of the changes on that issue, so I'm creating this one to address that.

**Comment by AgustinVallejo** [comment]
@DianaTavares please review and close. I think the new gradient is way more satisfactory

**Comment by DianaTavares** [comment]
looks good!!
