### ISSUE TITLE
Hide Block B density when only one block scene is selected in the explore screen

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#13]
Hide Block B density when only one block scene is selected in the explore screen

![Screen Shot 2021-04-29 at 4 46 46 p m](https://user-images.githubusercontent.com/26031501/116623276-a0a78680-a90b-11eb-8e51-4326b10253e0.png)

**Comment by jonathanolson** [comment]
Implemented above, however I'd like feedback on the layout:

If we reduce the size of the accordion box to fit (when block B isn't visible), this would shift the collapsed/uncollapsed version of it down by default. Keeping the top of the accordion box the same is probably possible, but has its own trickiness.

How should the layout here work?

**Comment by DianaTavares** [comment]
I just open the PhET test and the density of block B still in the Density readout when only one block is selected.

About the layout, I like it more when the accordion box stays in the same position, and it only increases its size when it shows the B block density:

![image](https://user-images.githubusercontent.com/26031501/120525751-18028700-c39e-11eb-9292-5e7eb44f8493.png)


![image](https://user-images.githubusercontent.com/26031501/120525772-1f299500-c39e-11eb-9788-083d2940d7f2.png)

Isn't this the same behavior that the Mass/volume controls when one block or two are selected? the control stays at the top, in the same position, and it only increases or reduces its length if one or two blocks is selected.

**Comment by jonathanolson** [comment]
Added the desired layout above, can you try it out? Do we need to adjust other spacing?

**Comment by DianaTavares** [comment]
it is working! yes, space is going to be adjusted, because the vectors scale control needs to be added to the forces panel, but this issue was about the density readout behavior and it is working well. I am going to open a new issue about the scale vector control, and the position of the controls.  then I am going to close this issue.
