### ISSUE TITLE
% submerged in the boat screen should to display the value of the boat, not the block. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#130]
#112 indicates that for the applications screen (boat), 

> Observe that the name in the panel said "% Boat submerged" because in this case, we want to know the percentage of the boat and not the block.

![image](https://github.com/phetsims/buoyancy/assets/26031501/109c753d-762e-4423-90b1-ddb9af5a37b6)
 
but in the actual version, we have the block:
![image](https://github.com/phetsims/buoyancy/assets/26031501/d4c7512e-2653-4d25-b47a-ee272b91bc65)

- [x] we need to change the block for the boat in this panel. I like much more how the word “boat” is not in the title, and better close to the percentage! The panel then needs to be: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/660d15fc-0a31-43eb-9999-7f3c25e73c7b)

Also, reviewing the issue #112 there is conversation about making this panel (and density) 
> I'm also wondering if we should have the accordion boxes float up when closed

That action will make the simulation more clean! 

- [x] in all screens, make the % submerged panel float to adjust its positions according to the density panel (close or open).

**Comment by zepumph** [comment]
Let me know if I can help at all.

**Comment by AgustinVallejo** [comment]
This is done. However, as it was mentioned in the design meeting, because of the way the submerged % is calculated, the boat shows by default a 100% immersion even when floating, because the buoyant force is naturally bigger than its weight (that's how it floats).

Tracking in https://github.com/phetsims/buoyancy/issues/134 how to handle that and closing this one.

**Comment by zepumph** [comment]
Looks like it still says "Block". Likely it is best to let DL give a spot check on this kind of stuff, just to be sure. 

![image](https://github.com/phetsims/buoyancy/assets/6856943/b11a80ae-0cd6-4593-9ed0-b3d98d864f28)

**Comment by DianaTavares** [comment]
Yes, this need to said "Boat"

**Comment by AgustinVallejo** [comment]
Done!
