### ISSUE TITLE
Changes in position and size of some controls

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#133]
- [x] move the 1/2 block and bottle/boat radio button close to the rest button, and make them smaller to fit in the “Shapes” screen. 
- [x] Center the Fluid density control with the pool
Here are the mock-ups:
**Explore**
![image](https://github.com/phetsims/buoyancy/assets/26031501/6e21ff8a-95bd-488e-bee6-b574aa4f6cc6)

**shapes**
![image](https://github.com/phetsims/buoyancy/assets/26031501/a5464872-ff4c-42ee-9ee3-1c83dc1c910f)

**Applications**
![image](https://github.com/phetsims/buoyancy/assets/26031501/8831f854-435a-4420-b2c6-a642cd6f67a5)

- [ ] move the gravity control in the Lab screen to the right. Observe how, in this screen, to fit the scale control, the Gravity panel, and the readouts (Density and %submerged) require having a smaller width. 
- [ ] Center the Fluid density control with the pool in this screen as well.

![image](https://github.com/phetsims/buoyancy/assets/26031501/d67389eb-4ce8-4384-bfc8-5e5930673493)

- [ ] Convert density and submerged readouts floating panels

**Comment by AgustinVallejo** [comment]
@DianaTavares we were discussing about this issue. While the radio button repositioning seems nice, and it's already done, we advice against moving the gravity panel in Lab. It currently looks like this

![image](https://github.com/phetsims/buoyancy/assets/37052186/e59f1eb3-d567-4801-83e6-ac9bbe4a2f29)

The vertical space is currently just right for us not to shrink either the height-slider or the accordion boxes, which would start looking small for translations for them to fit. We understand that the desire is to have Fluid Density Panel centered for all screens, but we feel like those two panels are good the way they are right now in Lab Screen.

Let me know what you think :)

**Comment by zepumph** [comment]
@DianaTavares agrees that it is more cost to move the gravity panel over. All else was reviewed. Closing
