### ISSUE TITLE
Rename LiquidDensityControlNode to FluidDensityControlNode

### ISSUE THREAD

**Issue by samreid** [phetsims/buoyancy#137]
The UI is labeled "Fluid Density":

<img width="425" alt="image" src="https://github.com/phetsims/buoyancy/assets/679486/8dc60dcd-9a92-42ec-a869-d5b97aa926cc">

So it would be nice to rename the LiquidDensityControlNode to make it more aligned with the UI. @AgustinVallejo or @zepumph I am happy to do this if it sounds good to you.

**Comment by zepumph** [comment]
Yes please, let's do it.

**Comment by samreid** [comment]
I renamed the file and a few parameters.  Want to rename these as well?

```ts
  public readonly liquidMaterialProperty: Property<Material>;
  public readonly liquidDensityProperty: TReadOnlyProperty<number>;
  public readonly liquidViscosityProperty: TReadOnlyProperty<number>;
```

**Comment by zepumph** [comment]
Yes please!

**Comment by zepumph** [comment]
I think those should say because they are PhET-iO instrumented and Density is published. Were there any other API changes in density from your changes? Feel free to close.

**Comment by samreid** [comment]
No API changes in the commits above. Sounds good to keep those variables to match with Density. Closing.
