### ISSUE TITLE
The boat volume control should control de exterior volume 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#14]
The Boat Volume control and readout in the Aplicacionts screen at this moment shows the inside volume of the boat:

![image](https://user-images.githubusercontent.com/26031501/117038161-efb73800-accc-11eb-849f-60dcf992b566.png)

It needs to be modified to control and show the full volume of the boat. That is the data needed to calculate the max buoyancy force that the boat can generate, and then calculate the weight that the boat can carry.

![Screen Shot 2021-05-04 at 11 40 33 a m  (2)](https://user-images.githubusercontent.com/26031501/117039169-10cc5880-acce-11eb-834f-1f6a719c67fa.png)

**Comment by jonathanolson** [comment]
I checked the code, and it's using the exterior displaced volume of 5L (or whatever the "Boat Volume" is in the control) currently. I was able to get it arbitrarily close to 105L, with mouse imprecision. Can you verify?

Also, if a student pushes the boat near the limit, dropping it in water will not put it at its equilibrium point immediately, so it will likely sink if close to that value.

**Comment by DianaTavares** [comment]
I review it and the behavior is good. I get very close to 5L. The volume is showing the exterior volume of the boat. 

![Screen Shot 2021-06-18 at 7 33 53 p m](https://user-images.githubusercontent.com/26031501/122625750-54a3d300-d06c-11eb-9fe5-311ddf4da21e.png)
