### ISSUE TITLE
Boat cannot partially fill with water

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#143]
From design meeting.

https://github.com/phetsims/buoyancy/issues/131

* 1. If every you would fill the boat a little, then instead fill it all the way up.
* 2. We need a delay in filling, such that it takes some amount of time/depth underwater in order to trigger a complete fill. This will help with bouncing when dropping the block into the boat from high up.

**Comment by AgustinVallejo** [comment]
Closing this one to be addressed in #142
