### ISSUE TITLE
Fluid displaced layout is above ground

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#144]
Since adding [depth lines](https://github.com/phetsims/buoyancy/issues/117), the fluid-displaced panel is now above the ground. 

![image](https://github.com/phetsims/buoyancy/assets/6856943/fef5909d-e8dd-4f73-b332-9219f01e391b)

@DianaTavares, how do you recommend we get rid of the vertical space?

**Comment by zepumph** [comment]
Here is what it looks like when I make the checkbox vertical spacing consistent with the bottom chunk:

<img width="605" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/c7918141-962a-443b-99c9-7a4496ec8afc">

**Comment by DianaTavares** [comment]
I was witting just about that! It looks amazing! Now all the checkboxes are equally distributed

**Comment by DianaTavares** [comment]
I don't love that the margin on the top is smaller than the margin of the panels on the bottom, and that the space between the panels is not equal distributed. 

![image](https://github.com/phetsims/buoyancy/assets/26031501/26b168e6-e0fc-4669-bb18-75aa2d217b66)

Move the checkboxes panels down is move all the panels on all screens down, is that super hard? 
another option is to make the Fluid Displaced panel smaller to allow that these vertical space is equal in all the panels

This recommendation is only to make the simulations more beautiful, put I understand that is not related to performance. I am not sure if it is important to work on that.

**Comment by zepumph** [comment]
This was a bit complicated, but I got it working and I don't mind the code too much, @DianaTavares please let me know if this was what you were thinking about, and assign it back to me for next steps.

**Comment by zepumph** [comment]
@DianaTavares likes it! Closing
