### ISSUE TITLE
Possible to drain water from the pool!

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/buoyancy#145]
When testing https://github.com/phetsims/buoyancy/issues/142 I thought I had introduced a bug, but it seems to have been there for a while. If you fuzz test only screen 5, it's possible to drain the pool from its contents. I have a hunch as to what could be the cause but have to investigate.

![Image](https://github.com/phetsims/buoyancy/assets/37052186/8cfb307e-2cd3-4fb9-9064-427f10fb668f)

**Comment by AgustinVallejo** [comment]
Found it! If in the Bottle scene you take the pool scale out, every time you switch scenes, some water is going to be missing.

**Comment by zepumph** [comment]
Likely because how this is behaving in non standard cases? 

https://github.com/phetsims/density-buoyancy-common/blob/21fdf30579e3aeeb9b703598527dbf861f51a9b1/js/buoyancy/model/BuoyancyApplicationsModel.ts#L129-L133

**Comment by AgustinVallejo** [comment]
Pushed a fix and fuzz tested it. Seems to be working correctly now :)

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
