### ISSUE TITLE
Wrong physics when submerging a block onto a boat

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/buoyancy#147]
After talking today with @jonathanolson,  @zepumph and @samreid, it seems the physics for the boat are still off... Even though we removed the option to have a little bit of liquid in the boat, there's still the possibility of having a filled boat, dragging a block into it's volume, and having wrong physics when the block enters the boat domain. 

Some of the problems discussed:

1. If the boat is in static equilibrium (i.e. buoyant force = -weight), when the block goes in and displaces internal liquid, the boat goes up... This was a long discussion and the reason for this being wrong is still not clear to me.
2. When the boat is fully submerged, right now the displayed weight is `BoatMass + MassOfLiquidInside` and when the block goes in, this weight diminishes. The calculation will be changed in https://github.com/phetsims/buoyancy/issues/142 but this is still a symptom of what's apparently wrong with the model.

**Comment by samreid** [comment]
Maybe we should look at this in standup?
