### ISSUE TITLE
add more materials to the boat scene 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#15]
Add the materials that the Explore screen has (styrofoam, wood, ice, brick, aluminum) to the materials in the boat scene in the applications screen: 

![image](https://user-images.githubusercontent.com/26031501/119080456-bf0b1a00-b9bf-11eb-8dbc-47e56751dccc.png)

It is possible that less dense materials can cause effects or desires in the simulation. In that case, remove the materials from the list that are causing the failures.

**Comment by jonathanolson** [comment]
Added the materials in the order noted (at the end). If you want a different order, let me know!

I'll rely on QA tests to see what materials we may need to remove.

**Comment by DianaTavares** [comment]
Thanks, @jonathanolson. The order of the materials should be from the less dense to the dense, then the Styrofoam, Wood Ice Brink, and Aluminium should be at the top of the list, over Pyrite. 

I play a little bit with all the materials and the behavior of the simulations looks good.

**Comment by jonathanolson** [comment]
Sorted by density, can you verify?

**Comment by DianaTavares** [comment]
Nice work, thanks!!
