### ISSUE TITLE
Dev version for interviews

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#151]
We are ready for interviews, and the invitations have been sent! 
Hope you can help me with the dev version! Thanks :D

**Comment by zepumph** [comment]
On it.

**Comment by zepumph** [comment]
Deployed: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.6/phet/buoyancy_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.6/phet-io/

Deployed: https://phet-dev.colorado.edu/html/buoyancy-basics/1.0.0-dev.1/phet/buoyancy-basics_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/buoyancy-basics/1.0.0-dev.1/phet-io/

**Comment by DianaTavares** [comment]
![image](https://github.com/phetsims/buoyancy/assets/26031501/7fd30228-f2df-4fd1-ad9b-e0e8bb7de004)
 Masses and weight labels are in the corner of the screen of the dev version of Buoyancy

**Comment by DianaTavares** [comment]
I also don't see the vectors: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/c5f321eb-3b43-46b9-b230-f80f2679c9bd)

**Comment by AgustinVallejo** [comment]
Will try deploying a newer one!

**Comment by AgustinVallejo** [comment]
Deployed dev.7 and this error is still present :/

**Comment by samreid** [comment]
I worked on a related problem in https://github.com/phetsims/density-buoyancy-common/issues/118, perhaps we also need to update the decoration layer during startup? Not sure why that would be needed in built but not unbuilt.

**Comment by AgustinVallejo** [comment]
@samreid helped me fix this, these ones should work.

Deployed: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.8/phet/buoyancy_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.8/phet-io/

Deployed: https://phet-dev.colorado.edu/html/buoyancy-basics/1.0.0-dev.2/phet/buoyancy-basics_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/buoyancy-basics/1.0.0-dev.2/phet-io/

**Comment by DianaTavares** [comment]
Thanks working wel!!
