### ISSUE TITLE
modify the total volume of fluid of the pool to 100L wiht the scale in

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#16]
The volume of the pool with the scale inside the fluid is 101.80L when no object is inside it. 
![image](https://user-images.githubusercontent.com/26031501/119081048-d3034b80-b9c0-11eb-990d-94e2330f7d68.png)

It is important for students to know the volume of displaced fluid for calculating the Buoyancy force, that is easier if the volume of the pool is 100L with the scale inside, where most of the time of interaction is going to be.

**Comment by jonathanolson** [comment]
Added compensation for this for all 4 screens, can you verify?

**Comment by DianaTavares** [comment]
It is great. Thanks!!
