### ISSUE TITLE
On buoyancy: Applications it is easy to lose the block behind a control panel

### ISSUE THREAD

**Issue by samreid** [phetsims/buoyancy#164]
On buoyancy: Applications it is easy to lose the block behind a control panel

<img width="294" alt="image" src="https://github.com/phetsims/buoyancy/assets/679486/703b33d6-8ff4-4968-a7b6-d821e943d8fe">

@DianaTavares can you please advise?

**Comment by DianaTavares** [comment]
the plane should behave like the panels in the other screens, like a wall that does not allow to put the blocks (bottle/bot) behind them.

**Comment by samreid** [comment]
@AgustinVallejo volunteered to work on this, thanks!

**Comment by AgustinVallejo** [comment]
Fixed, closing
