### ISSUE TITLE
Readouts should only show one decimal place when over 10.0

### ISSUE THREAD

**Issue by samreid** [phetsims/buoyancy#167]
To help with oscillations like those described in https://github.com/phetsims/buoyancy/issues/64#issuecomment-2138615315, we agreed that numeric readouts should only show one decimal place when over 10.0.

**Comment by AgustinVallejo** [comment]
Pushed a simple fix for this. So far it's only in the scales, but let me know if all the other numbers should also have this. Or just the ones affected by the flickering (contact force readout)

**Comment by AgustinVallejo** [comment]
This is done, closing

**Comment by lesha724** [comment]
@AgustinVallejo, Thanks
