### ISSUE TITLE
The behavior of the boat going down in the pool is strange 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#17]
The boat doesn’t sink once that is under the water, it needs to go more under the surface to fill with the fluid and then sink like is shown in the next gif: 

![boatsinking](https://user-images.githubusercontent.com/26031501/119081591-e6fb7d00-b9c1-11eb-83d4-3c658550072e.gif)

The ideal behavior is that once the boat is under the surface, the fluid gets inside the boat and it sinks.

**Comment by jonathanolson** [comment]
Finally got this identified, should be fixed in master!

**Comment by DianaTavares** [comment]
It works nicely. thanks!!
