### ISSUE TITLE
Move the liquid properties from the DensityBuoyancyModel to Pool

### ISSUE THREAD

**Issue by samreid** [phetsims/buoyancy#170]
From https://github.com/phetsims/buoyancy/issues/86#issuecomment-2146135590 we would like to move the liquid properties from the DensityBuoyancyModel to Pool. We will also add a `liquid` tandem so things will nest nicely in the studio tree

**Comment by samreid** [comment]
Pushed with migration rules. Cannot close yet since I still have to do this part:

> We will also add a liquid tandem so things will nest nicely in the studio tree

**Comment by samreid** [comment]
Fixed above and would be good for a spot check from @zepumph. Please close if OK.

**Comment by zepumph** [comment]
Looks great thanks.
