### ISSUE TITLE
In Shapes, the max width is not maintained when changing to another shape. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#174]
I create a block with the mas height and width, but when I change it to invert code, even that the sliders are in max, the object is smaller. I also add other inverted cone to compare. When I move, the slider starts to work correctly. 
![Untitled](https://github.com/phetsims/buoyancy/assets/26031501/c99f0ca5-5eb2-471a-a458-d4ca8ee412ee)

**Comment by samreid** [comment]
@AgustinVallejo is working on this problem as part of https://github.com/phetsims/density-buoyancy-common/issues/204, closing as duplicate.
