### ISSUE TITLE
Create examples.md

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#176]
Related to #51 

Doc here: https://docs.google.com/document/d/10Y-sdlFu0rm_1tfCoM4IRakP2gdKZMSTAh8JS1aXwhg/edit#heading=h.tjvj76cxjx9v

Let's use this issue to keep track of things to document in examples.md
- [x] How to customize the blocks/objects on each screen
- [x] Helpful things to know about scales such as...
     - EDIT: This is now obsolete. <s>Measured value is `scaleForceInterpolatedProperty`</s>
     - [x] To fix the height of the pool scale, hide its slider, which will also disable dragging the scale itself.
-  EDIT: This is now obsolete. <s>How to extract data about the blocks/fluid using `materialProperty`. 
     - Note that internal units for volume are m<sup>3</sup> but the view uses L. 
     - For the bottle, the density is that of the bottle/material system.
     - Include example about how to get values from the API like this:</s>
     ```ts
   (await phetioClient.invokeAsync( 'buoyancy.compareScreen.model.blockSets.sameMass.block1A.materialProperty', 'getValue' )).density;
     ```
- [x] Model vs. View units, see https://github.com/phetsims/density-buoyancy-common/issues/266

**Comment by arouinfar** [comment]
I created examples.md for both [Buoyancy](https://github.com/phetsims/phet-io-sim-specific/blob/main/repos/buoyancy/examples.md) and [Buoyancy: Basics](https://github.com/phetsims/phet-io-sim-specific/blob/main/repos/buoyancy-basics/examples.md) in the above commits. A few of the items listed in https://github.com/phetsims/buoyancy/issues/176#issue-2365243954 are no longer relevant, so I crossed those out.

@DianaTavares please review these documents and let me know if there is anything you'd like me to add.

**Comment by DianaTavares** [comment]
The examples area amazing!! I follow all instructions and work perfectly! Very well described, and I can't think of something else that needs to be described here. Great job Amy!!
