### ISSUE TITLE
Create Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#177]
@DianaTavares let's use this issue to keep track of the issues that need to be documented in the Teacher Tips.

Buoyancy Basics draft is ready for review here: https://files.slack.com/files-pri/T5QBX4DGB-F0793RW6G3U/download/buoyancy_basics.pages?origin_team=T5QBX4DGB

**Comment by arouinfar** [comment]
@DianaTavares I reviewed and revised the Teacher Tips and uploaded them to the [SharePoint folder](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FBuoyancy%20HTML5&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa).

Quick overview of the changes:
* Grammatical fixes and minor rewording.
* Added all supported public query parameters to the Customization Options section.
* Updated the links to point to the eventual home of Buoyancy: Basics. (We should test these once the sim is published to make sure I didn't make a mistake).
* Removed sound section because this sim only supports UI sound, not full sonification.

Please review and let me know if you have any questions.

**Comment by DianaTavares** [comment]
Love it @arouinfar, thanks for your feedback. I took that document to create the one for Buoyancy, the links in the custom part are almost all wrong, but for me is easier to wait until the sim is published. Please help me to review also this document: [Buoyancy Teacher Tips](https://o365coloradoedu.sharepoint.com/:u:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Buoyancy%20HTML5/[buoyancy-html-guide.pages](https://o365coloradoedu.sharepoint.com/:u:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Buoyancy%20HTML5/buoyancy-html-guide.pages?csf=1&web=1&e=qajjmc)?csf=1&web=1&e=qajjmc)

**Comment by arouinfar** [comment]
@DianaTavares the Buoyancy tips look great! I made a few minor edits and uploaded the updated version to SharePoint. Once the sim is published, we should export to PDF and check the links.

Feel free to close this issue, or leave it open as a reminder for when the sim is published.

**Comment by DianaTavares** [comment]
Yeah! Thanks I will close it. Don't worry, I will remember to submit it once the sim is ready to publish!
