### ISSUE TITLE
the default block volume in the boat scene indicate 5L, but it is 3.46L 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#18]
When the boat screen is just open, or it is refreshing, the volume of the block indicates 5 L in the slider, but when we put it in the pool, it only indicates 3.46L 

![image](https://user-images.githubusercontent.com/26031501/120523807-fa342280-c39b-11eb-8d6b-43ba83a059af.png)

The mass value of the block is correct, then it changes the density of the block. For example, in this screen the ice sink, but in the explore screen it doesn't, and the mass is the same:

Boat scene: 
![image](https://user-images.githubusercontent.com/26031501/120524177-63b43100-c39c-11eb-9c25-2c685db5a15a.png)

Explore screen:
![image](https://user-images.githubusercontent.com/26031501/120524242-762e6a80-c39c-11eb-853f-d18d7e2c477e.png)

Once that I move the sliders (mass or volume) this bug disappears and the size of the block is what the slider indicates.
![image](https://user-images.githubusercontent.com/26031501/120524390-a249eb80-c39c-11eb-9b94-25207c5d8b4e.png)

**Comment by jonathanolson** [comment]
This ends up in a buggy state because the slider won't allow any mass above 27kg, however a 5L steel (default) block would take more than that.

What should the desired behavior/ranges be for the block? How should that work?

**Comment by DianaTavares** [comment]
The original mockup has a range of 0-110 kg for the mass control, and 1-5 for the volume. But it only has denser material 
![image](https://user-images.githubusercontent.com/26031501/122625146-31c3ef80-d069-11eb-969e-e2132e78e6c4.png)

The new version has a volume range of 1-10, in that way the mass needs to go to 215 kg and include all the material, like styrofoam. 

If we use the same behavior and design for the mass control that the intro screen, the restriction of values for the styrofoam is going to be ridiculously small. I don't think these materials are going to be very popular on this screen, and users at this point should know that they can modify the mass throw the volume. I think that is better to have coherence between screen. Then I suggest the same behavior that the other screens, the mass goes to 0-215 kg, with a gray restriction depending on the material.

One option is to reduce the volume ranges from 1 to 5 L, in that way the mass can go from 0-110 only. 

I would like to know @arouinfar opinion about this or bring this question to the design meeting.

**Comment by DianaTavares** [comment]
an issue related to the mass range was opened (#31). then we can close this.
