### ISSUE TITLE
Updates to bottle, block, boat controls on Applications Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#180]
Related to #51. Since the Applications Screen only exists in Buoyancy, the `buoyancy` repo seems appropriate for this issue, but apologies in advance if it should go in `density-buoyancy-common`.

On the Applications Screen, the panel in the upper-right corner contains all of the controls associated with the bottle, boat, and block. Here's what the panels and tree structure currently look like for each scene.

| Bottle | Boat |
| --- | --- |
| <img width="339" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/45127feb-46da-452b-b2a4-dfe5584a38cb"> | <img width="334" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/b020e7c1-623e-4f39-bfce-2ef8885691ed"> |
| <img width="308" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/6bf43dd2-cc37-43ca-8f2f-b5bde665d5e5"> | <img width="360" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/9d8d7dfb-05f9-4e99-93f1-c2ba4561ce28"> |

@DianaTavares and I reviewed these controls and would like to make some changes:

- [x] The name `bottleControlNode.insideMaterialControlNode` implies that it includes everything above the divider line, including `customBottleDensityNumberControl`. Is it possible to make `customBottleDensityNumberControl` a child of `insideMaterialControlNode`? That way, setting `insideMaterialControlNode.visibleProperty` to `false` will hide everything above the dividing line. Currently, it looks like this if a non-custom material is selected. 
       <img width="200" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/dcc0176a-439f-4706-b6f6-0fa5eb847ca0">
* For `bottleControlNode.insideMaterialControlNode.massNumberControl`...
    - [x] This contains lots of useless children. It looks like this display was created by hiding the irrelevant components of the NumberControl. I'm able to make the slider/buttons visible in the tree, but nothing happens in the view. Can we uninstrument all children except for the `visibleProperty`?
       <img width="200" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/3113802d-fc6d-44f5-a9d2-b3371513b76f">
    - [x]  Assuming we can uninstrument the children, can we also rename it to `massDisplay`? The "NumberControl" bit seems like an implementation detail and doesn't provide useful context.
    - [x] There are dynamic layout issues when setting `visibleProperty`to `false`. A hole is left behind in the panel:
       <img width="251" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/31f1064f-19fa-4381-b21e-9bcfffc3f34e">
- [x] Instrument "Air Volume" readout under `bottleControlNode.airVolumeDisplay` and give it a `visibleProperty` that is `phetioFeatured: true`.
- For `model.objects.boat.displacementVolumeProperty`...
    - [x] Add link under `boatVolumeNumberControl.slider` pointing to this. 
    - [x] Range should match Boat Volume slider.
    - [x] ~Name is unclear. Rename to `boat.totalVolumeProperty`, with `phetioDocumentation` to be added over in https://github.com/phetsims/density-buoyancy-common/issues/232.~ Will be done in https://github.com/phetsims/density-buoyancy-common/issues/245
- [x] `blockControlNode.massNumberControl`: There needs to be a way to permanently hide the MassNumberControl, regardless of whether it is the high/low density variety. Unfortunately, this doesn't look like an instrumented thing we can just add a `visibleProperty` to.
- [x] ~There are dynamic layout issues with the Block's `*DensityMassNumberControl`. For example:~ Will be done in https://github.com/phetsims/density-buoyancy-common/issues/246
      <img width="200" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/7d0febde-529a-4f90-bb40-0c1e236e763f">
- Other things to rename:
  - [x] `bottleControlNode` > `bottleControls`
  - [x] `insideMaterialControlNode` > `materialInsideControls`
  - [x] `blockControlNode` > `blockControls` 

      

Assigning to the dev team.

**Comment by AgustinVallejo** [comment]
> [boat.displacementVolumeProperty] Range should match Boat Volume slider.

I see @zepumph unified those ranges here https://github.com/phetsims/density-buoyancy-common/commit/32624356967482f40095dfad7b6181af8bcb3322 but the one in the model is in m^3, then multiplied to be L in the view. Is that good as is, or should something change there? @arouinfar @zepumph

**Comment by arouinfar** [comment]
> [boat.displacementVolumeProperty] Range should match Boat Volume slider.

Apologies, this was a bit unclear.  Model units of volume should always be m<sup>3</sup>,  so when I ask for the "range to match", I mean the range should be the equivalent to what we use in the view. So 1-10L would be 0.001-0.01 m<sup>3</sup>

**Comment by AgustinVallejo** [comment]
Most of this is done, one question for @arouinfar:
> Name [boat.displacementVolumeProperty] is unclear. Rename to boat.totalVolumeProperty

Bottle also has a displacementVolumeProperty, should that change as well?

And I might need further help on this:

> There are dynamic layout issues with the Block's *DensityMassNumberControl. For example:

I added stretch: true to some components that supported them, like the containers for normal VolumeNumberControl or MassNumberControl. But the *Density ones are children of a BooleanToggleNode, which doesn't support stretching. So i'm not sure how to proceed here.

**Comment by AgustinVallejo** [comment]
Moved the above mentioned items to https://github.com/phetsims/density-buoyancy-common/issues/245 and https://github.com/phetsims/density-buoyancy-common/issues/246

Now this is ready for review

**Comment by arouinfar** [comment]
Overall, these changes are looking good.

> For `bottleControlNode.insideMaterialControlNode.massNumberControl`...
> This contains lots of useless children.

Things are looking much better on main. Here's what the tree structure currently looks like:
<img width="342" alt="image" src="https://github.com/phetsims/buoyancy/assets/8419308/a136ed9f-85bd-4b8e-9b95-ad0f5aea104e">

Is there a reason why `enabledMassRangeProperty` is still instrumented? 

- [x] If it's safe to uninstrument `enabledMassRangeProperty`, please do so.

> Instrument "Air Volume" readout under `bottleControlNode.airVolumeDisplay` and give it a `visibleProperty` that is `phetioFeatured: true`.

- [x] `bottleControls.airVolumeDisplay.visibleProperty` should be `phetioFeatured: true`.

Back to @AgustinVallejo.

**Comment by AgustinVallejo** [comment]
The above is done, back to Amy

**Comment by arouinfar** [comment]
Looks great, thanks @AgustinVallejo. Closing.
