### ISSUE TITLE
Create `model.objects` grouping for Shapes Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#182]
For https://github.com/phetsims/buoyancy/issues/51

Lots of great changes happened over in https://github.com/phetsims/density-buoyancy-common/issues/182, and the contents of `model.objectA` and `model.objectB` are perfect. 

However, some additional organization in the tree would be helpful and make the Shapes Screen more consistent with other screens.

Let's create `model.objects` to contain the objects-related elements. Here's a mockup of the desired structure:
```
- model
  - objects
     modeProperty
     materialProperty
     + objectA
     + objectB
``` 

Assigning to @AgustinVallejo.

**Comment by AgustinVallejo** [comment]
Passing back to @arouinfar for review. Please assign back to me when done as I'm currently discussing this with devs:

> Got an error commiting due to unused eslint-disable. However, the condition still applied, i.e. tandem name is different to variable, I just called createTandem from another tandem. So I assume that lint rule looks for options.tandem.createTandem?? I removed the eslint comment and pushed but not feeling totally confident about it
Is it okay to remove?
Should I change the variable name to match tandem in this case?

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo the updated tree structure looks good on main. Back to you for the remaining work.

**Comment by AgustinVallejo** [comment]
The only dev suggestion was to change the variable name, so I did above. Closing.
