### ISSUE TITLE
 Bottle, custom option: the mass readout doesn't change after 100 kg. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#183]
Here is the evidence: The mass readout in the bottle continues changing, but the one that indicates the mass of the material doesn't change after 100 kg. 
![Untitled](https://github.com/user-attachments/assets/d1d7ada2-aa1d-4dc5-9d42-d74cf35f80b6)

**Comment by samreid** [comment]
Fixed, @DianaTavares can you please test?

**Comment by DianaTavares** [comment]
It is working, thanks!!!
