### ISSUE TITLE
Zero-volume boat behavior

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/buoyancy#19]
For the applications screen with the boat, it's meant to scale down to zero volume in the slider. I've just applied a few fixes for handling this better in master, but I'm curious how the zero-volume boat should act.

For instance, it currently tracks it in the physics system. The zero-volume boat can (invisibly) fall to the bottom of the pool.

Is that what is desired?

**Comment by DianaTavares** [comment]
The minimum volume a.lowed for the boar should be 1L. Change the control values from 1 to 20.  Also, the Boat Volume slider should snap in 0.1 L steps.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by DianaTavares** [comment]
the minimum volume of the boat is perfect! but the slider should change the volume in steps of 0.1L and it is doing it in steps of 1L.

**Comment by jonathanolson** [comment]
I believe this is adjusted with the above patch, can you verify?

**Comment by DianaTavares** [comment]
I tis working perfectly! thanks!!
