### ISSUE TITLE
Applications screen scales with a boat

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/buoyancy#20]
It seems like it's possible to move the pool scale currently on this screen. Since the implementation currently only handles properly placing the block in the boat, placing the scale in the boat results in buggy behavior.

Can we fix the scale to the ground on this screen?

**Comment by DianaTavares** [comment]
Yes, lets fix the scale in the pool

**Comment by jonathanolson** [comment]
Implemented above, closing.
