### ISSUE TITLE
minimum fluid density value of 0.5 kg/L, and modification in the slider steps 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#21]
The minimum value for the Fluid Density control should be 0.5 kg/L, and the buttons with the arrows, the change in the density value should be in steps of 0.01 kg/L.

**Comment by jonathanolson** [comment]
Implemented above. I also removed "Air" as a combo box option (I believe this was discussed), let me know if that's not desired.

**Comment by DianaTavares** [comment]
It is perfect, thanks!
