### ISSUE TITLE
Scales can move in all screens except in Applications

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#24]
In the August 12 design meeting, it was agreed to allow the scales to move in all screens except in the Applications screen. 

**Scales in the Applications screen**

The scales in the applications screes are not draggable because we don't want that students place them inside the boat. Their positions need to be fixed with the next characteristics: 

1) The scale in the pool needs to be placed more to the right, not allowing to place the smaller block between the edge of the pool and the scale. like this:

![image](https://user-images.githubusercontent.com/26031501/129218334-e966d71b-702a-4168-ab47-62bdf4ad3e26.png)

2) The scale in the ground needs to be at the right of the pool with a distance from the edge that does not allow a small block to be placed there.  In the default view of the boat scene, the scale and the bock should be placed as is shown in the next picture:
![image](https://user-images.githubusercontent.com/26031501/129632911-cd3a15ad-350b-459c-b75b-70c139c490b5.png)

Also, in the Intro screen, the scale is over the edge, and the invisible wall is beyond the edge 
![image](https://user-images.githubusercontent.com/26031501/129215219-8efd78be-005c-45a8-801b-4b55d81ba143.png)

I like the position of the invisible wall in Density (not at the edge of the screen).  we can apply this to all screens in Buoyancy, placing the invisible wall a few distances from the edge of the window. 

Density screenshot:
![image](https://user-images.githubusercontent.com/26031501/129216157-3200e9ad-1df0-4ee3-a2b6-70d043e2e434.png)

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

> The scale in the ground needs to be at the right of the pool with a distance from the edge that does not allow a small block to be placed there.

That's not possible, since the user can resize the window to be wider.

**Comment by DianaTavares** [comment]
Nice, I like how the scales work and where they are placed.
