### ISSUE TITLE
Reset button for the boat screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#25]
The boat can have fluid inside, but we need a way to get the fluid out. It is necessary to add a reset button that is going to leave all the controls in the same configuration, and just place the boat and block to their default position.

this picture shows the position of the reset button: 

![Screen Shot 2021-08-16 at 1 18 05 p m](https://user-images.githubusercontent.com/26031501/129610897-ef3051e3-a103-43c0-93d9-c6aa5278be85.png)

The button has the same design used in gravity and orbits.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by DianaTavares** [comment]
I love it. Thanks!
