### ISSUE TITLE
Vector Scale control

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#26]
The simulation has a big range of vector values and is necessary to fit all of them, on the screen. It is necessary to add a "Vector Scale"  control in the "Forces" panel like is shown in the picture: 

![image](https://user-images.githubusercontent.com/26031501/129256656-b450d73e-6d39-4d4e-8e81-405ea94cea29.png)

The biggest vector has a magnitude of 2102.10 N, and the smaller is 0.98 N. What should be the range of values for the vectors' scale buttons? I was using px as a reference, but these are not the numbers/units used in the code. @jonathanolson suggested in the design meetings creating a tool to allow designers to measure the length in the units that are used in the code. 

All vectors need to fit in the screen when the blocks are in the pool. once that the measuring tool is ready,I will create an array for the zoom levels.

**Comment by jonathanolson** [comment]
Measuring tool is ready. Ctrl + Shift + H in a simulation will bring up an interface, where I can move it out of the way and select "Measuring Tape":

<img width="450" alt="image" src="https://user-images.githubusercontent.com/480878/158666684-e209c3e7-4b35-40a9-8cde-a618410df770.png">

**Comment by DianaTavares** [comment]
The tool is super cool! but how do I stop (hide) the measuring tape to have again a interactive simulation? I need to do several measures of the block at different sizes and now I have been reloading the simulations

**Comment by DianaTavares** [comment]
By using the measuring tape, I identify that the range of "view-units" that can be well visualized in the sim is **between 20 view-units and 170 view-units** 
![image](https://user-images.githubusercontent.com/26031501/160955138-daee3330-034e-4057-9b74-16babbaa9d90.png)

I played with the magnitude of vectors in each screen and the report is in [this document](https://docs.google.com/spreadsheets/d/1CDAJzqa8A6pFA_ETCC1TKqjs_Mzl7bm7EBzaviXvuvU/edit#gid=0).  

the Vector Scale control needs 9 steps, starting in 1N = 20 view-units, and each step divides the view-units between 2, making the 1N arrow smaller:
![image](https://user-images.githubusercontent.com/26031501/160957674-2ee107ba-37da-49f9-82f0-6682c07b8318.png)


in that way, the default "step" and "Newtons to view-units" for each screen are:

- Intro screen, step 4:  1N = 1.25 view-units
- Explore screen, step 4: 1N = 1.25 view-units
- Shapes screen, step 2: 1N = 5 view-units
- Applications screen, step 4: 1N = 1.25 view-units

**Comment by jonathanolson** [comment]
Implemented above, can you see how it looks?

**Comment by pixelzoom** [comment]
@jonathanolson It looks like you missed a usage of ZoomButtonGroup in CCK.  I'm seeing these tsc errors, and something similar in CT.

```
../../../circuit-construction-kit-common/js/view/ZoomControlPanel.ts:46:12 - error TS2345: Argument of type ‘NumberProperty’ is not assignable to parameter of type ‘RangedProperty’.
 Type ‘NumberProperty’ is not assignable to type ‘{ range: Range; readonly rangeProperty: IReadOnlyProperty<Range>; }’.
  Types of property ‘range’ are incompatible.
   Type ‘Range | null’ is not assignable to type ‘Range’.
    Type ‘null’ is not assignable to type ‘Range’.
46   super( selectedZoomProperty, providedOptions );
        ~~~~~~~~~~~~~~~~~~~~
../../../circuit-construction-kit-common/js/view/CCKCChartNode.ts:205:65 - error TS2345: Argument of type ‘NumberProperty’ is not assignable to parameter of type ‘RangedProperty’.
205   const zoomButtonGroup = new MagnifyingGlassZoomButtonGroup( this.zoomLevelProperty, {
```

**Comment by pixelzoom** [comment]
I took a stab at fixing CCK in the above commit. @jonathanolson or @samreid please review.

**Comment by samreid** [comment]
The commit https://github.com/phetsims/circuit-construction-kit-common/commit/dbff07b543ec353e661dbd58a01a0bd6e52df99d looks good, thanks.

**Comment by DianaTavares** [comment]
The behavior is what I expected. It works amazing!! 

I am not sure if the error with the code commented by @pixelzoom is fixed, then I leave you @jonathanolson  to close this issue.

**Comment by jonathanolson** [comment]
Closing, thanks!
