### ISSUE TITLE
Change default block and boat values in the boat scene 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#27]
the first interaction with the boat should be with a block that can be placed in the boat and float. Then the default value should be modified to 

 block: pyrite 1L, and the boat volume of 10L

![image](https://user-images.githubusercontent.com/26031501/129265330-cc1e81fe-0883-41b4-9c6e-f41b509d683f.png)

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by DianaTavares** [comment]
It is working, but.. Students need to place the very carefully the block to not sink the boat. I thinking that still not being the best first interaction with the sim. Let's change the pyrite for a less dense object. @jonathanolson, can you change the material for Brick?

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by DianaTavares** [comment]
nice, thanks!!
