### ISSUE TITLE
Modify the range of values in the Shapes screen

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#29]
The shapes screen allows very small blocks. The range for the controls Height and Width should be modified to go from 10 to 20 cm.

**Comment by DianaTavares** [comment]
Add a control that allows changing the material of the blocks, with the same materials option that the explore screen. The next image shows the position of this material's control and how the  1-2 blocks screen needs to move its position. This new position for the scene buttons need also be modified in the explore screen.   
![Screen Shot 2021-08-16 at 6 40 41 p m](https://user-images.githubusercontent.com/26031501/129642284-baebb029-5b76-4213-9c3e-86c70564eba1.png)

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by DianaTavares** [comment]
The smaller volume of a block in the shape's screen should be 1L, and now is 0.06L

![image](https://user-images.githubusercontent.com/26031501/159810591-d2eb9113-2aac-4dde-bf68-150cfd6ac0c6.png)

About the max block's volume,  we discuss that it should be 8L (like it is at this moment). But for consistency around all screens, which max blocks' volume of 10L,  the Shapes screen should also have a max volume for blocks of 10L. 

I use the Measuring Tape to show the smaller view units that the block should measure when  Height and Width are in the minimum value (both in the minimum should generate a 1L block):

![image](https://user-images.githubusercontent.com/26031501/159811622-6d453457-c0da-4f6f-9933-5ffd6e33aa35.png)

and when Height and Width are in the max value, the block should have a volume of 10L

![image](https://user-images.githubusercontent.com/26031501/159812229-3ccb77b8-f235-471a-b89e-9200ca77d352.png)
 
The screenshots show the most precise measurements I could make.

**Comment by jonathanolson** [comment]
Ahh, I did not understand the desired ranges! It sounds like the ideal is a cube that goes from 1L to 10L. That's implemented above, does that look good?

**Comment by DianaTavares** [comment]
The block is amazing! goes from 1L to 1L. But the other shapes still allow a very small volume. 
The other shapes need to have the same minimum Height and Width as the block (but because of their shape, they are going to have different volumes).

**Comment by jonathanolson** [comment]
Implemented above, the other shapes should have equivalent min/max sizes. Can you see how this looks?

**Comment by DianaTavares** [comment]
amazing, thanks!!
