### ISSUE TITLE
Mass control in the boat scene need two mass ranges. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#31]
The mass control in the boat screen at this moment goes from 0-27 kg:
![image](https://user-images.githubusercontent.com/26031501/130511296-172d7bd5-707f-4135-8285-4890af4f6710.png)

But the mass material in this screen goes from 0.15 to 214.5 kg. If we apply the same behavior that the other screens, with a slide that covers all this range, it is going to be difficult to notice the mass range for styrofoam, ice all the material with lower density.  The suggestion is to have two mass ranges for this screen:

- One for the materials from styrofoam to aluminum that goes from 0.15 to 27. When the user selects a material between styrofoam and aluminum, the mass slider is going to show this range, and limit the mass according to the material. 

![image](https://user-images.githubusercontent.com/26031501/130540954-97ebef3c-f08f-4449-a943-58ed67098357.png)

- the other mass range for Pyrite to Platinum goes from 0 to 215 kg. also the slider is going to be limited according to the material.

In order for the user to know that the mass range is different, this mass control has the ranges in number on the top of the slider, as is shown in the picture: 
![image](https://user-images.githubusercontent.com/26031501/130541266-ea73bb4b-3b36-4dbf-ba56-3f777d60632a.png)

Also, the Custom option should be included in the second mass range, with all the mass values available.

**Comment by zepumph** [comment]
@DianaTavares and I discussed this, and saw how the volume slider could be buggy for platinum since the mass range doesn't go high enough. Over to her to continue to think through the best options for the ranges given the available materials.

**Comment by DianaTavares** [comment]
I reviewed this with the teachers interview, and they wanted gold in the list. That means that the mass slider needs to go to a big range, and the 2 ranges of values for the mass are necessary, as is described in the first paragraph:

* materials from styrofoam to aluminum that goes from 0.15 to 27
* materials from Pyrite to Platinum (including custom)  goes from 0 to 215 kg

**Comment by zepumph** [comment]
This has been implemented above. @DianaTavares please review. Note that the min of the range stays the same between the two ranges; we liked this for continuity. Anything else here? Feel free to close.

**Comment by DianaTavares** [comment]
it is amazing!!

The only observation is the custom option that only goes up to 10 kg:

![image](https://github.com/phetsims/buoyancy/assets/26031501/c1c55bb4-6b3b-46cf-9354-cb65310776ef)

I would like that it goes up to the 215 kg.

**Comment by zepumph** [comment]
Amazing! That was what I was thinking too. This will be handled over in https://github.com/phetsims/buoyancy/issues/115. I'll assign that issue to review to make sure custom ranges seem right to you. Thanks.
