### ISSUE TITLE
new position of the density readout and other controls. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#32]
In order to add the "Vector scale" control in the vectors panel, and because the density is related to the blocks and this value needs to be close to the blocks control, the "Density-readout accordion box" has a new position in all the screens. Other controls/buttons also change their position in the screens as is mentioned next: 

**Intro**
![image](https://github.com/phetsims/buoyancy/assets/26031501/867ff47d-fa33-4336-a115-bdedd2276a52)

**Explore Screen** 
On this screen also the one/two blocks radio button changes its position. 
![image](https://github.com/phetsims/buoyancy/assets/26031501/7bc8dae4-456e-4a34-b5ff-7b56a3305390)

**Shapes Screen** 
Also the one/two blocks radio button changes its position
![image](https://github.com/phetsims/buoyancy/assets/26031501/5813b978-3019-45b5-be8e-7a63f549d8fd)

**Applications Screen / bottle**
The "Material inside" panel is placed closer to the green area in the ground, and that makes space to place the density readout below that panel. 
![image](https://user-images.githubusercontent.com/26031501/130542262-322460cc-7c4f-4237-89b4-f3ccadaffab4.png)

**Applications Screen / boat**
same that bottle, the block/boat panel needs to be moved up, and place the density read out bellow this panel. Th
![image](https://user-images.githubusercontent.com/26031501/130542539-9b0cf426-d3fc-4bcb-95f0-d2fb039b1e23.png)

**Comment by AgustinVallejo** [comment]
The above commit addresses some of this requests. We're still missing Intro and Applications screen to implement, since their right panels behave a bit differently.

**Comment by AgustinVallejo** [comment]
Closing this issue as this is being discussed in the common component issue: https://github.com/phetsims/density-buoyancy-common/issues/105
