### ISSUE TITLE
small modifications in the text of some controls and the size of one slider. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#33]
- [x] For consistency across screens, the text "Height" and "Width" in the controls in the shapes screen need to be bold:

no bold in this screen: 
![image](https://user-images.githubusercontent.com/26031501/131744011-6bfe7142-7c43-48b9-89aa-c2a580d61997.png)

bold in all the other screens:
![image](https://user-images.githubusercontent.com/26031501/131744039-7db6391f-dade-42c4-96e4-c0c76f9ae0af.png)

- [x] the slider in the boat volume control needs to be smaller. Match its side with the other sliders in the sim.

Boat volume with big slider:
![image](https://user-images.githubusercontent.com/26031501/131744399-bd0ddae0-b0fc-4d4c-aea5-d0dd905d3d5d.png)
 
The other sliders in the sim are smaller:
![image](https://user-images.githubusercontent.com/26031501/131744457-0192e424-321a-4130-9124-91cb5037257d.png)

- [x] for consistency, the text "Fluid" in the intro screen, and "Fluid density" in the other three screens need to be bigger. Match the size of the word Gravity in the screen explore. For that, the Fluid density control needs to be a little bigger, as is shown in the next picture: 
![image](https://user-images.githubusercontent.com/26031501/137783413-aeba761b-6863-44c8-b9ce-2d355ac037c8.png)

**Comment by jonathanolson** [comment]
Implemented above, can you verify? I also increased the "Fluid" label on the bottom of the 1st screen to match (if that looks wrong, let me know).

**Comment by DianaTavares** [comment]
Thanks, @jonathanolson.  These are other changes that I identify:

1. Height and Width in the Shapes screens are bigger than the other controls' names in a panel. They need to have the same size that Mass and Volume text in the Explore screen. 

![image](https://user-images.githubusercontent.com/26031501/159808926-af117df9-e84d-45bb-a707-bb0fbf43205e.png)
![image](https://user-images.githubusercontent.com/26031501/159809064-deee2e37-65dd-4c82-9caf-c2be70f84c25.png)

2. For consistency, all the blue sliders should have the same size. Change Hight, Width, and Boat Volume sliders to match the size of Fluid Density and Gravity sliders.  

![image](https://user-images.githubusercontent.com/26031501/159809555-a10c6f5b-5441-4b17-bd92-1b45a3027161.png)

**Comment by jonathanolson** [comment]
I believe I've updated the font and slider thumb sizes, can you verify and see if it looks good?

**Comment by DianaTavares** [comment]
Now I see that other texts don't have the same size.   

1.- All the **Bold** should have the same font size. Let's use the **Mass** text as the base and modify the Fluid Density, Gravity, Forces, and Density, in all screens

2.- All the text that is not bold should also have the same size. Using the "Water" text in the Fluid Density menu as the base, modify all the not bold text in the Forces and density panel on all screens, and the Volume the shapes screen: 
![image](https://user-images.githubusercontent.com/26031501/179596483-53b8ddb7-8832-4a81-a194-842351b17cfc.png)


and the Air Volume in the Applications screen, Bottle scene:
![image](https://user-images.githubusercontent.com/26031501/179597870-e6b9e6db-1dc6-4519-bb58-daed562fce6e.png)


3.- Make that all the blue sliders look the same. In the sim, the Height and Width in the shapes screen, and the Boat Volume in the Applications screen (boat scene), the slider move like in a short white rectangle; modify that the slider moves in an horizonal line, with little liens in the extremes, like a de fluid density slider.
![image](https://user-images.githubusercontent.com/26031501/179600367-e444415c-e4fd-4799-90db-be8063a6fe93.png)

**Comment by jonathanolson** [comment]
> 1.- All the Bold should have the same font size. Let's use the Mass text as the base and modify the Fluid Density, Gravity, Forces, and Density, in all screens

This applies to the Density sim also. I'm assuming you're meaning the "Mass" title for the slider (14px bold?) - That would result in size reductions for:

1. Density intro screen "Density (kg/L)" accordion box
2. Block labels (but probably not tweaking those?)
3. Scale labels (but probably not tweaking those?)
4. Density compare screen "Blocks" title for the radio buttons
5. Density compare screen "Mass" / "Volume" / "Density" title on the middle-right control
6. Density mystery screen "Density Table" accordion box title
7. Density mystery screen "Material" and "Density (kg/L)" headers in the density table (hopefully not tweaking those?)
8. Density mystery screen "Blocks" title for the radio buttons
9. Buoyancy intro screen "Forces" on bottom-left
10. Buoyancy intro screen "Fluid" on center-bottom
11. Buoyancy explore screen "Density" and "Forces" on bottom-left
12. Buoyancy explore screen "Fluid Density" and "Gravity" on center-bottom
13. Buoyancy explore screen density readout in the bottom-left (red/blue text) (hopefully not tweaking those?)
14. Buoyancy shapes screen "Density" and "Forces" on bottom-left
15. Buoyancy shapes screen "Fluid Density" on center-bottom
16. Buoyancy applications screen "Density" and "Forces" on bottom-left
17. Buoyancy applications screen "Fluid Density" on center-bottom
18. Buoyancy applications screen "Material Inside" on bottom-right

**Comment by jonathanolson** [comment]
> 2.- All the text that is not bold should also have the same size. Using the "Water" text in the Fluid Density menu as the base, modify all the not bold text in the Forces and density panel on all screens, and the Volume the shapes screen:

Value readouts and tick marks are smaller, presumably I could ignore those?

**Comment by jonathanolson** [comment]
I believe (3) should be handled in the above commit, can you verify?

**Comment by DianaTavares** [comment]
1.- **Bolde Text**:  Now that I see the list and the text in the sim, I realize that the different sizes are because the bigger texts are panel titles, and the smaller texts are variables inside that panel. Do not modify those. Sorry for that!  

2.- yes, you can ignore those.

3.- the change looks amazing!! 

Then, to close this issue, we need just make all the text that is not bold the same size, ignoring readouts and tick marks. I think that makes the text in the Forces panel smaller and the "volume" in the left panels in Shapes and Applications get bigger.

**Comment by jonathanolson** [comment]
> I think that makes the text in the Forces panel smaller and the "volume" in the left panels in Shapes and Applications get bigger.

Things should be at 14px if they're not bold with the above commit. I'm not sure what you mean would be smaller in the Forces panel?

**Comment by jonathanolson** [comment]
Anything else to do after the above change?

**Comment by DianaTavares** [comment]
it is perfect, thanks!!
