### ISSUE TITLE
update ranges of the Boat volume

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#34]
On the 08/26 design meeting, we agree that a 1L boat is not useful for the interaction with the sim. Then the minimum value for the boat volume should be 5L.

and about the max volume, can the boat be bigger?  Can the boat be wider, almost to the back of the pool? in that way, the boat can be shorter, and make it easier to take the block out, and if it is possible to have a bigger max volume.

**Comment by jonathanolson** [comment]
Implemented above. 30 seems like a workable large range, how does this look?

**Comment by DianaTavares** [comment]
It looks amazing and works very well. Thanks @jonathanolson
