### ISSUE TITLE
Built version doesn't load on Safari

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/buoyancy#4]
**Console output:**
[Error] SyntaxError: Multiline comment was not closed properly
	(anonymous function) (buoyancy_en_phet.html:20659)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (p2.js, line 0)
[Error] ReferenceError: Can't find variable: p2
	(anonymous function) (buoyancy_en_phet.html:58382:94)
	__webpack_require__ (buoyancy_en_phet.html:24407)
	(anonymous function) (buoyancy_en_phet.html:24422)
	(anonymous function) (buoyancy_en_phet.html:24422)
	attemptStart (buoyancy_en_phet.html:63510:86)
	timeoutListener (buoyancy_en_phet.html:63511)
	(anonymous function) (buoyancy_en_phet.html:63511:94)
	Global Code (buoyancy_en_phet.html:63512:147)

Can highlight the text on the loading screen - really weird:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5090275/75497748-7ca48a00-5982-11ea-913d-c268cf73e49c.png">

**Comment by jonathanolson** [comment]
Hmm, interesting. I just built a version (after the es6 module stuff), and it seems to be working in my Safari. Would it be best to publish a dev version?

**Comment by oliver-phet** [comment]
@jonathanolson I just tried again to build from phettest and I'm getting the same behavior.

**Comment by jonathanolson** [comment]
I see that it's failing on phettest (won't even launch in Chrome on my end), investigating.

**Comment by jonathanolson** [comment]
Looks like this was exposed when we stopped uglifying builds on phettest.

This results from the comment in our 3rd party physics engine:
```js
/**
 * The array type to use for internal numeric computations throughout the library. Float32Array is used if it is available, but falls back on Array. If you want to set array type manually, inject it via the global variable P2_ARRAY_TYPE. See example below.
 * @static
 * @property {function} ARRAY_TYPE
 * @example
 *     <script>
 *         <!-- Inject your preferred array type before loading p2.js -->
 *         P2_ARRAY_TYPE = Array;
 *     </script>
 *     <script src="p2.js"></script>
 */
```

where the end-script tag messes up the file (if comments aren't stripped).

**Comment by jonathanolson** [comment]
Tagging for developer meeting, since it would be good to discuss debug builds, and whether we should be doing some work on them to remove or filter specifically this type of change, or what in general.

**Comment by jessegreenberg** [comment]
This is the same as https://github.com/phetsims/chipper/issues/787, the decision was
> Maybe we could consider minification for debug builds (but with beautified output and without stripping assertions or mangling)?

**Comment by jonathanolson** [comment]
Added workaround for this case, closing.
