### ISSUE TITLE
add a materials combobox in the shape screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#43]
Add materials Combobox with the same options of the explore screen to the shapes screen. Both blocks will change their material when users use this control. 
The position of this control is shown in the next screenshot: 
![Screenshot 2021-12-31 at 18 16 40](https://user-images.githubusercontent.com/26031501/147833750-9f5de5e1-722f-4ada-8a2d-6a9536319aca.png)

**Comment by zepumph** [comment]
I got to a commit point on this, adding a materialProperty to the model, and using it for applying to both masses. Still lots to do before I push:

- [ ] The combo box should maximize the width of the panel
- [x] The density accordionbox should update based on the new material
- [x] Move `MaterialControlNode` to a new file,
- [x] Awkwardness about using a PrimarySecondary... Node for 3 things (hacks).
- [x] We shouldn't allow a custom material option since there is no way to adjust the custom material.
- [ ] Noting that there can be some layout overlap with the two-block radio buttons:

    <details>

    ![image](https://github.com/phetsims/buoyancy/assets/6856943/1df4fef6-c0b6-46fb-8372-3b8cb3e09d9b)

**Comment by zepumph** [comment]
> The density accordionbox should update based on the new material


This feels related to https://github.com/phetsims/buoyancy/issues/75.

**Comment by zepumph** [comment]
I think now is a good time to check in with @DianaTavares, though there are still two pixel polished about. I'll see what she thinks.

**Comment by DianaTavares** [comment]
It is perfect! thanks!!

**Comment by zepumph** [comment]
There are two questions left in https://github.com/phetsims/buoyancy/issues/43#issuecomment-1928036656. Can you confirm that nothing more is needed?



> * The combo box should maximize the width of the panel [(to match the mockup)]
> * Noting that there can be some layout overlap with the two-block radio buttons:

**Comment by DianaTavares** [comment]
>  The combo box should maximize the width of the panel

I find it more elegant when combo boxes match panels size, but most of them in the sim don't match. Then it is ok that in this case also doesn't match. Example with Explore:
![image](https://github.com/phetsims/buoyancy/assets/26031501/56e595ae-392c-481c-b053-d3da4b49841d)
 

> Noting that there can be some layout overlap with the two-block radio buttons

The density readout needs to move according to these mockups in #32, then I think is not needed to fix here the relationship of this panel with the radio buttons. 

> Can you confirm that nothing more is needed?

For me is strange the color of some shapes, I think that is because the “light” of the simulations.. came from the top? 
![image](https://github.com/phetsims/buoyancy/assets/26031501/5c274db2-b8be-42d5-bbe1-290d6ff6099a)

![image](https://github.com/phetsims/buoyancy/assets/26031501/df8c159b-323c-4f8c-8847-4d7d57ba502b)


The overlapping is also strange:
![image](https://github.com/phetsims/buoyancy/assets/26031501/48ffd2a3-d2e3-4f9d-a4d1-1e2d895c2aef)

**Comment by zepumph** [comment]
Excellent. Thanks. I created side issues for the other bugs you reported.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
