### ISSUE TITLE
User request: Allow "g" to be either 9.8 or 10 m/s/s

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/buoyancy#45]
>  Allow "g" to be either 9.8 or 10 m/s/s. I have worked with that sim a lot. The idea being that many of these sims are used by 9th graders and younger where using g = 10m/s/s is the standard. It would make the number work out MUCH better!

@DianaTavares I thought we have had this request before, but I'm not finding any issues.

**Comment by DianaTavares** [comment]
I like this request. It is true that younger students use g=10 m/s^2. I think that the solution can be a query parameter.  What do you think about this @arouinfar? do you think this is enough or is better to have a control in the sim to allow these changes in g?

**Comment by arouinfar** [comment]
> I thought we have had this request before, but I'm not finding any issues. 

We have received somewhat similar feedback for Projectile Motion used in the context of a math class, https://github.com/phetsims/projectile-motion/issues/226. The idea is the same -- 32 ft/s^2 is a nice number for g.

> I like this request. It is true that younger students use g=10 m/s^2. I think that the solution can be a query parameter. 

I like this idea, but the [model already uses g=9.8](https://github.com/phetsims/density-buoyancy-common/blob/master/js/common/model/Gravity.ts#L67) (not 9.81). The gravitational force on a 5.00 kg object is exactly 49.00 N, and the value of Earth g on the Explore screen is 9.80 m/s^2.
<img width="137" alt="image" src="https://user-images.githubusercontent.com/8419308/159985008-1124d6a3-ec76-40e1-a5de-7d6eb3418e8b.png"> <img width="257" alt="image" src="https://user-images.githubusercontent.com/8419308/159985400-6243a0e7-d235-4310-a611-54b38ba046cf.png">

One possibility would be `gEarth=rounded` and `gEarth=precise` to switch between g=10 and g=9.8.

**Comment by DianaTavares** [comment]
I really like the idea of an option for g=10 on all screens, not even for younger learners, also for older students to make faster calculations on the applications screen.

I like this @Amy suggestion:
>One possibility would be gEarth=rounded and gEarth=precise to switch between g=10 and g=9.8.

But my worry is how this is going to affect the explore screen, where the user can change the gravity. @jonathanolson, can the sim has these query parameters? do they affect the gravity control in Explore?

**Comment by arouinfar** [comment]
> But my worry is how this is going to affect the explore screen, where the user can change the gravity. 

My proposal would change the value of Earth's g. For screens without a gravity control, g=10 m/s^2. For the Explore screen, the default would still be Earth and the displayed value would be 10 m/s^2.

**Comment by jonathanolson** [comment]
Perhaps the query parameter could just take a numeric value (in m/s^2)? `gEarth/earthGravity=9.81`, `gEarth/earthGravity=9.8`, `gEarth/earthGravity=10` would all be possible, or another alternative value could be used. Thoughts? Presumably it would affect everywhere earth's gravity is used (that includes the initial value in the Explore screen).

**Comment by DianaTavares** [comment]
I like @jonathanolson idea of a query parameter that can take a numeric value. My worry is that can take any value  (negative, cero, super big values) because it is hard to communicate in a query parameter the range. I think is better just to have a query parameter that makes the g default value equal to 10, and think in a name that communicates that in an easy way, like `g10`

**Comment by DianaTavares** [comment]
we decide to add the query parameter `gEarth` where users can choose a number between 9 and 10. 

Notify users about this option in the teacher tips.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by DianaTavares** [comment]
I works amazing, thanks!!

**Comment by oliver-phet** [comment]
User emailed that this feature will be added in the future version!
