### ISSUE TITLE
Add blocks' labels in the shapes screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#46]
The shapes screen doesn't have labels in its blocks: 

![image](https://user-images.githubusercontent.com/26031501/160958147-8db77fac-adca-40a0-8e78-ac244f1c84f1.png)

add labels in the upper left corner, Regardless of whether the label is outside the figure:
 
![image](https://user-images.githubusercontent.com/26031501/160958250-94dc1c01-0938-4b4b-9ae9-ff2724689661.png)

**Comment by jonathanolson** [comment]
Implemented above, can you see how it looks?

**Comment by DianaTavares** [comment]
Working!!
