### ISSUE TITLE
Screen icons 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#48]
Here are the screen icons (working in 3D in illustrator is difficult, I hope @jonathanolson, you can do it with code): 

Intro
![image](https://user-images.githubusercontent.com/26031501/160961192-c56021ed-13e5-46c8-a3e7-2e9bcdf16eec.png)

Explore
![image](https://user-images.githubusercontent.com/26031501/160961221-d99fea64-bc8b-451a-9599-5e8bda44bfcd.png)

Shapes
![image](https://user-images.githubusercontent.com/26031501/160961245-b20a6523-03f6-4c26-bde0-648c763e85c7.png)

Applications 
![image](https://user-images.githubusercontent.com/26031501/160961276-019bd214-2da9-4390-b02e-665d9c5cddfc.png)

**Comment by zepumph** [comment]
I wonder if we are going to want to promote these to `svg` images instead of png. I know a lot of work has been getting done _n this area with @marlitas and @amanda-phet with their publications. I'll assign back to @DianaTavares to investigate.

**Comment by amanda-phet** [comment]
I don't see any image files or ai assets in this sim's code. Are the 3D objects in the sim being drawn using code? If so, can the screen icons be made with code? 

If these need to be drawn with 3D tools we should not use svg. But if I can see the ai asset I might be able to give better suggestions.

**Comment by zepumph** [comment]
Oh I see, yes I totally got this issue wrong. I saw the above as pngs and went the wrong direction with it. We should definitely use the code to draw these Nodes. Sorry for the confusion!

**Comment by zepumph** [comment]
- [x] Don't forget about the lab screen icon, mockup in: https://github.com/phetsims/buoyancy/issues/113#issue-2164139232:

![image](https://github.com/phetsims/buoyancy/assets/26031501/fe257efd-e23a-47f4-8442-744457b2a560)

**Comment by samreid** [comment]
I added the lab screen icon and it currently looks like this:

<img width="465" alt="image" src="https://github.com/phetsims/buoyancy/assets/679486/7b2cd68a-5bee-416d-a76f-396c5f5db467">

It was unclear from the mock-up if we need to create a cartoon wireframe of the scale, or if it was a placeholder for the actual scale. So I started here. Anything can be adjusted or changed.  @zepumph or @DianaTavares can you please advise?

**Comment by zepumph** [comment]
It was a placeholder for the actual scale icon. The above is looking nice, thanks!

**Comment by zepumph** [comment]
@AgustinVallejo will take intro and applications. 

@zepumph will take shapes and explore and updates from @samreid's first pass of the lab screen


We may still be blocked until this issue is closed: https://github.com/phetsims/buoyancy/issues/141

**Comment by zepumph** [comment]
https://github.com/phetsims/buoyancy/issues/141 is complete, and there is a nice and easy way to use `getThreeIcon` and `getAngledIcon` for the screen icons. See usages for buoyancy scale/boat/bottle icons and the density screen icons. Marking off hold.

**Comment by zepumph** [comment]
I would consider these done:

Explore: 
<img width="521" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/adbee1fb-d287-4f6e-8abe-d620525347d9">


Shapes: 
<img width="443" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/69943293-cd26-4764-9aad-c45a37204955">

**Comment by AgustinVallejo** [comment]
I think this is ready for review by @DianaTavares

**Comment by DianaTavares** [comment]
looks amazing!!

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by zepumph** [comment]
This shouldn't have been closed. I haven't tightened up the lab screen icon yet. Glad the others are in good shape though!
