### ISSUE TITLE
User request: increased precision

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/buoyancy#5]
> I really like your simulations, but for the buoyancy simulator, I am 
> trying to design a simulation revolving around tracking water masses in 
> the ocean. I am limited because ocean density changes are significant at 
> the part-per-thousand (and smaller) levels of change. Having PhET only 
> go to 3 significant figures is problematic, leading me to have 
> unrealistically large gradients in temperature and salinity in order to 
> see the effect of changes in water density (the problem is even worse 
> for limnological simulations, and forget about trying to show subtle 
> effects of mixing leading to things like cabeling).
> 
> It seems like it would be trivial to me to make it possible to enter 3 
> or four digits of accuracy after the decimal point to the simulation. 
> Maybe you could put that on your "wish list" of changes?
>

**Comment by DianaTavares** [comment]
This issue was discussed in desing meeting May 20, 2021. 
The user sugestion goes beyond the scope of the simualtion and it is not goign ot be implemented. The sim is for learning porpuse, and not for the reseacrh that the user is suggestion. closing.
