### ISSUE TITLE
Second object control in the shapes screen is not working

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#50]
When I click on the second block icon on the shapes screen, nothing happens. The second object doesn't appear.
![secondbutton](https://user-images.githubusercontent.com/26031501/162336830-edbc212b-be6c-4d65-9144-78b50ff51afd.gif)

**Comment by jonathanolson** [comment]
I believe I handled this with https://github.com/phetsims/density-buoyancy-common/commit/84d56abfbf6535ce15f953248dd82809f14d7edb, can you verify?

**Comment by DianaTavares** [comment]
working perfectly!
