### ISSUE TITLE
Rename forceScaleProperty to vectorScaleProperty

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#53]
For #51 

The property hooked up to the vector scale zoom buttons is `model.forceScaleProperty`. I found this naming to be a bit unclear, and my first assumption was that it was somehow related to the scales (which measure a force). Let's change it to `vectorScaleProperty`.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks!
