### ISSUE TITLE
Add labels A and B to the blocks in the intro screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#55]
In order to make it easier to identify the blocks in the intro screen, add labels A and B in the corner of each block. Block A is the block to the left, and B is the block to the right. 

The behavior of these labels should be the same that the blocks in the [mystery screen in Density](https://phet.colorado.edu/sims/html/density/latest/density_en.html?screens=3) (with background and black text)

**Comment by jonathanolson** [comment]
The labels in the Density mystery screen don't use A/B, but instead e.g. 2A, 2B. I can't tell what the desired behavior is. I implemented the second option in the commit above, can you check this (and let me know if you want A/B instead?)

**Comment by DianaTavares** [comment]
I like it  this way, thanks @jonathanolson!!
