### ISSUE TITLE
Updates to Scales

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#56]
For #51 

- [x] Change tandem names to `scale1` and `scale2` instead of using left/right/pool language.
- [x] `inputEnabledProperty` should be phetioReadyOnly: false.
- [x] `scaleForceInterpolatedProperty` should be phetioHighFrequency: true.

**Comment by AgustinVallejo** [comment]
All three requests done in the above commits. Just some questions left for @arouinfar. I noticed the three following behaviors, let me know which ones are ok or which ones we should change.
1. When inputEnabled is set to false, the scale doesn't change in appearance at all, but cursor still changes to pointer when hovering.
2. When inputEnabled is false, or by default the scale is not movable, it's not possible to access it with alt+hover. You have to look for scale1 in the studio tree. 
3. If the scale was not movable by default, like in Application Screen, changing inputEnabledProperty doesn't do anything. It'll never be movable as of now.

**Comment by zepumph** [comment]
This issue has been complicated by the addition of the poolScaleHeightControl. In some screens that have that, the scale hooked up to the slider in the pool is called `poolScale`. The other scale is still scale1. This doesn't seem ideal. @arouinfar can you help?

If we like `poolScale`, should it be nested under the `pool` tandem?

**Comment by zepumph** [comment]
From discussion with @arouinfar @AgustinVallejo @DianaTavares @samreid:

- [x] move `poolScale` into the Pool, and called `pool.scale`.
- [x] `scale1`->`scale`.
- [x] Add phet-io doc to `scale` saying "the one that starts on the ground" or something.

**Comment by samreid** [comment]
Fixed as prescribed, closing.
