### ISSUE TITLE
Treat blocks on Intro screen like those in the Mystery Screen of Density

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#57]
For #51 

We would like the blocks on the Intro Screen to be customizable like the blocks on the Mystery Screen of Density (`materialEnumProperty`, `customDensityProperty`, editable mass, etc.).  

@jonathanolson mentioned that there is a flag/option that would do this for us, so assigning to him.

Note that #55 requests the addition of Mystery Screen-style label tags, so perhaps these issues can be consolidated.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson!
