### ISSUE TITLE
Instrument text lablels in blocksRadioButtonGroup

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#59]
For #51 and similar to https://github.com/phetsims/density/issues/134

Clients may want to customize the text labels on the Blocks Radio Buttons, so let's instrument them.
<img width="129" alt="image" src="https://user-images.githubusercontent.com/8419308/170184574-ac05d468-2b8e-4df3-9650-a56c77414916.png">

**Comment by jonathanolson** [comment]
Implemented (and instrumented the radio button group too), but the naming might need updates. `blockSetControl` is the internal name so that's what I gave it for now. Can you check what should be done?

**Comment by arouinfar** [comment]
Thanks @jonathanolson the functionality looks good in master. If we want to keep things parallel to  Density, we could call it `blocksRadioButtonGroup`.  I did, however, notice that the radio buttons themselves have nonsensical names in the Studio tree:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/8419308/174892479-0c96f6f8-b7ff-4921-b82f-5f54b2a4bc22.png">

**Comment by jonathanolson** [comment]
The placeholders are gone, and I changed the name to be consistent. Can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks!
