### ISSUE TITLE
Zoom feature does not apply to 3D graphics in this sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/buoyancy#6]
Noticed that the zoom feature does not zoom in on the 3D graphics. Disabling zoom for now in this sim until it can be sorted out.

**Comment by jessegreenberg** [comment]
From https://github.com/phetsims/joist/issues/659.

**Comment by ariel-phet** [comment]
@jonathanolson this would be a desirable sim to have zoom available in when published if easy to work around adjusting the webgl/shader code. If that is a difficult task, let's discuss.

**Comment by jonathanolson** [comment]
Main work done in https://github.com/phetsims/density/issues/50, added the flag to enable it. @jessegreenberg can you briefly verify?

**Comment by jessegreenberg** [comment]
Working much better! You may already be aware of this, but it looks like the ground is positioned relative to the navigation bar regardless of transform. Zooming into the nav bar looks OK but if you zoom above it there is white space -
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/6396244/114583511-a9336800-9c4f-11eb-9cc9-d9282ab2a403.gif)

**Comment by jonathanolson** [comment]
Handled in https://github.com/phetsims/density/issues/50, closing.
