### ISSUE TITLE
Add material ComboBox to Shapes Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#60]
Users should be able to change the material of the objects on the Shapes screen. Here's a mockup of the control panel:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/8419308/170185050-9feeef29-5d76-41a6-905e-f8a596ffa0e0.png">

The material ComboBox sets the material of **both** objects.

Assigning to @DianaTavares to confirm that this mockup is still accurate before assigning to @jonathanolson for implementation.

**Comment by DianaTavares** [comment]
yes, that mockup is accurate, but this issue is the someone that the #43. closing because is duplicated.

**Comment by arouinfar** [comment]
Oops, thanks @DianaTavares!
