### ISSUE TITLE
Instrumentation of objects on Shapes screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#61]
Related to #51 

The objects on the Shapes screen vary in shape (ellipsoid, cone, etc.) and have an adjustable height, width, and material (#43).
<img width="181" alt="image" src="https://user-images.githubusercontent.com/8419308/170185788-365e8c26-854d-4cf8-ba36-768a46da8d41.png">

In terms of PhET-iO customization, we want clients to be able to set the material, height, width, and shape type. The mass and volume should be read-only as those are derived.

Currently, the objects are dynamically created, so changing the shape type will destroy the old one a create a new one in its place. The object's material, height, width, and position will be preserved.

@jonathanolson is not sure about the best method for PhET-iO implementation and was considering using a PhetioGroup, but wants to consult with the PhET-iO team.

**Comment by jonathanolson** [comment]
This not being complete yet is causing the CT failure https://github.com/phetsims/buoyancy/issues/40.

@arouinfar Is a PhetioGroup desired for this (which would create a new phetioID each time the shape is created, which seems not great)? Would we want to have a separate instrumented object for each shape?

@zepumph and @samreid, is there anything I can do to essentially replace the singleton object here?

There's also a possibility of a significant refactor to the code, that would separate each Mass from its physical representation (so we could have a Mass switch from a cube shape to a cone, and it would just reset that part). We'd still have the problem of representing the changes of the physical part (e.g. it now has a radiusProperty and doesn't have a sizeProperty).

**Comment by samreid** [comment]
Brainstorming a pattern that may work: we don't have a precedent for this, but it would be like:

```ts
class MyDensityObject extends PhetioObject{
   private massObject = ...;
   setMassObject(massObject: MassObject){
      this.massObject = massObject;
   }
}
```

So there is one singleton PhetioObject instance, but it can have immutable implementations that get swapped out.  The MyDensityObject would have an IOType with appropriate methods, like `setToBlock(height:number,width:number)` etc.

**Comment by arouinfar** [comment]
> @arouinfar Is a PhetioGroup desired for this (which would create a new phetioID each time the shape is created, which seems not great)? Would we want to have a separate instrumented object for each shape?

This seems somewhat similar to https://github.com/phetsims/mean-share-and-balance/issues/60. There are a relatively small number of objects -- 2 objects x 6 possible shapes. A static approach seems reasonable here, and might make the tree a bit more human-readable.

@samreid's proposal also sounds fine to me.

I don't love the idea of using a traditional PhetioGroup because it doesn't feel like we are creating an entirely new shape when selecting one from the ComboBox. So the creation/destruction of the phetioElement is a bit unexpected conceptually. However, I understand that there are other constraints at play here, so if that's the best structure, so be it.

**Comment by zepumph** [comment]
Sorry we didn't update this issue. @jonathanolson and I made lots of progress on this in a 2 hour meeting yesterday. We are trying out using a heterogenous PhetioCapsule, that can tear down and recreate the primary mass. There are still issues with it, but in general it creates a nice way to have consistent tandem names no matter the object.

**Comment by jonathanolson** [comment]
Implemented with @zepumph. There are still some errors in the studio if the block type is switched.

**Comment by zepumph** [comment]
Until we get a handle on this issue, I removed buoyancy from phet-io state testing.

**Comment by zepumph** [comment]
From catching up and doing some testing locally, it looks like state for screen 2 (explore) is working well. I'll try to apply that pattern from above onto the shapes/application screens.

**Comment by zepumph** [comment]
Ok, to recap here:

* Intro screen: Statically allocated (different block instances per radio button scene, i.e. "Same Mass")
* Explore screen: Statically allocated (just a primary and secondary mass)
* Shapes screen: Uses PhetioCapsule, but is failing in the state wrapper
* Applications screen: The scene Property isn't instrumented yet, so I can't be 100% sure, but I think this is also going to be statically allocated.

I'll start with fixing the shapes screen.

**Comment by zepumph** [comment]
Ahh, the instrumentation here is solid, it was just a bug from over in https://github.com/phetsims/phet-io/issues/1810 where we stopped disposing capsule elements. I fixed things in the above. I believe we may be done with this issue now, though I did see a couple of state related problems while working here that I'm just going to add in before calling it.

**Comment by zepumph** [comment]
Ok. The shapes screen is looking good. I saw that many things were depending on the value of the `internalVisibleProperty`, but it wasn't instrumented, which was causing some wonkiness with state. I'm going to go ahead and close this issue, and we should create a new issue if more PhET-iO tasks are needed.

**Comment by zepumph** [comment]
This issue is not complete at all. Please see https://github.com/phetsims/buoyancy/issues/160. I didn't catch it in february because phet-io validation wasn't on, so we didn't catch the archetype-related assertions that have now pointed us to the problem.
