### ISSUE TITLE
Group blocks together in the tree and use more general names

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#62]
For #51 

The block tandem names should be more general. Currently there are names like `sameMassWood` and `sameDensitySmall` but we can create more context by nesting things in the tree.

- [x] Intro Screen: follow the same pattern as `density.compareScreen.model.blockSets`, and call each block `blockA` and `blockB`. (We are adding A/B labels in #55.)
- [x] Explore Screen: follow the same pattern as `density.introScreen.model.blocks` and call each block `blockA` and `blockB`. 
- [x] Shapes screen:  currently called `primaryMass` and `secondaryMass` but "Mass" is a loaded term. Let's use `objectA` and `objectB` instead.

**Comment by jonathanolson** [comment]
Tandem structure should match this... however should the shapes screen have an "objects" tandem group? Also, the Shapes screen uses capsules now.

**Comment by arouinfar** [comment]
Thanks @jonathanolson. The checked items all look good to me. 

>  however should the shapes screen have an "objects" tandem group? Also, the Shapes screen uses capsules now.

The capsule naming looks fine, but let's add a parent "objects" container, mirroring the structure of `exploreScreen.model.blocks`.

**Comment by samreid** [comment]
I added `object` levels for Shapes and also for the Applications screen:

<img width="301" alt="image" src="https://github.com/phetsims/buoyancy/assets/679486/1256be35-35e2-47e8-9213-9e9201d8bf5b">

This was straightforward and it seems all requests were addressed.  A lot of unrelated changes appeared in the new API file. I guess I should check with @zepumph that those were intentional?? Feel free to close the isssue.

**Comment by zepumph** [comment]
buoyancy isn't stable, so it isn't currently getting updated very often. I have started reupdating density, buoyancy, and buoyancy:basics whenever I change the PhET-iO API of any of them. But this is just within that last 2 days. Can we all start doing that? My bound command is: `grunt generate-phet-io-api --sims=buoyancy,density,buoyancy-basics`
