### ISSUE TITLE
New initial position of the send block in Explore screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#65]
In the simulation at this moment, the second block's initial opposition is over the first block and looks strange when the block appears and disappears.  

![SecondBlock](https://user-images.githubusercontent.com/26031501/170766658-8f08f43f-ea8c-47b0-b0b0-f994f7830bcd.gif)

Change its position as is shown in the next picture: 

![Screen Shot 2022-05-23 at 3 02 05 p m](https://user-images.githubusercontent.com/26031501/170766228-a791b7ad-7612-4655-ae92-d32b7f6ed3c5.png)

**Comment by jonathanolson** [comment]
Done in the above commit, can you verify?

**Comment by DianaTavares** [comment]
Nice, thanks!!
