### ISSUE TITLE
?fuzzPointers=2 error: "Cubic start should be finite: Vector2(-Infinity, 0)"

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/buoyancy#7]
From https://github.com/phetsims/aqua/issues/106, when running fuzz testing with ?fuzzPointers=2 the following assertion is thrown:
>Cubic start should be finite: Vector2(-Infinity, 0)

Assigning to the responsible dev for this repo.

**Comment by jonathanolson** [comment]
I just resolved an error that failed with that message, and now I can't reproduce. I believe this should be fixed.
