### ISSUE TITLE
"Boat" can fill up with water and cannot be drained

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#71]
While playing with the sim, I saw that the boat could fill with water and required a reset to get the water out of it. That, to me, seems like a usability concern. Should we make a button to empty? Should it have a little drain plug you can remove to drain (sounds hard)?

**Comment by zepumph** [comment]
@DianaTavares and I discussed this, and we noted that there is a reset button below the pool. She reached out to teachers about this very question. Over to her to decide how to proceed.

**Comment by DianaTavares** [comment]
In this case, the user needs to use the reset button below the pool. In the interviews with teachers, I observed that it is not a problem for them to identify this control and use it.
