### ISSUE TITLE
Brick goes entirely in boat and cannot be dragged out.

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#72]
If a brick (or any material cube) is small enough, it can get "stuck" in the boat. The only way I could remove it was by slingshotting it out of the boat to land on the other side of sim. That doesn't seem ideal. How do we support dragging the brick "over" the boat that is right in front of it. 

![image](https://github.com/phetsims/buoyancy/assets/6856943/e40c7ef5-8ade-439f-9f44-b7a793e6e0ae)

**Comment by zepumph** [comment]
@DianaTavares and I discussed this, and we noted that there is a reset button below the pool. She reached out to teachers about this very question. Over to her to decide how to proceed.

**Comment by zepumph** [comment]
As decided in design meeting today, if you press somewhere and it could be the boat or something else, always press the "other" item.

**Comment by zepumph** [comment]
@AgustinVallejo and I would like to start in this function here: 

https://github.com/phetsims/density-buoyancy-common/blob/ebd0fa499edead2ccece06f01b8a5a8c897c173f/js/common/view/DensityBuoyancyScreenView.ts#L819

Perhaps as easy as saying "handle the boat last". @AgustinVallejo will report back with questions.

**Comment by AgustinVallejo** [comment]
I believe the above fix fulfills this. Please review and close if done.

**Comment by zepumph** [comment]
Looks great thanks!
