### ISSUE TITLE
Applications Screen: Average density value doesn't update between boat/bottle

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#75]
The "Average" readout is stuck on the bottle density, and doesn't change when changing to the boat.

![image](https://github.com/phetsims/buoyancy/assets/6856943/6c82590c-e806-4f43-bb8a-be974970457d)

**Comment by zepumph** [comment]
@jonathanolson @AgustinVallejo and I were very confused by the definition of what the "Average density"  of the boat would be. 

In the design doc we had a separate key for "block" and "boat":
![image](https://github.com/phetsims/buoyancy/assets/6856943/d23fbebb-ef3b-4229-81dd-c8989c3fb4c0)


Some other questions that we had:
1. Do we include the block in the average when it is inside the boat? If we include the "block", then doesn't that change the "boat volume"? That seems confusing. 
2. How do we handle the density/volume when the boat has water inside of it?
3. What is the purpose of showing a density for the "boat"? We weren't sure it was too valuable for students calculating density.  The only valuable density we can think of is the "Material density" for the boat instead of the "average" or "boat" system density.

In general we are confused, and it may be best to have some more design guidance (especially centered around learning goals) before we wire this panel up to the "boat" application.

If we actually do need to calculate the average density of the boat+contents (mass/water), then we are worried about how confusing of a design it could be, and what the value of this is.

**Comment by DianaTavares** [comment]
You are right! The goal of the screen is to calculate the weight that a boat can carry without sinking, and we only need the weight of the material (and it is interesting to see its density9. That density panel in the boat screen should show only the block density. 
![image](https://github.com/phetsims/buoyancy/assets/26031501/a1b59fa8-c77d-4c10-9a73-0c94a645bd4d)

**Comment by zepumph** [comment]
Alright. This has been updated and we are now showing the current material of the block. I also through in the boat's material to always be available (aluminum). That feels helpful to me, but let me know if you'd prefer to not have that.

![image](https://github.com/phetsims/buoyancy/assets/6856943/3a7908da-5200-478e-b466-17f65f1e4daf)

**Comment by DianaTavares** [comment]
In the 02/08/23 design meeting, we decided to change the "Aluminum" for "Boat Body"

**Comment by AgustinVallejo** [comment]
For this, I created a new material called Boat Body with aluminum's same density (So now the boat is made out of boat heh). Alternatively we could have left the boat as aluminum but catch the displayed name on the densityReadout. @zepumph Let's discuss which option sounds better, and if changing material feels okay, please review the above commit.
