### ISSUE TITLE
Support dynamic locale

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#77]

**Comment by zepumph** [comment]
Benchmark:

Screen 1:

<details>

![image](https://github.com/phetsims/buoyancy/assets/6856943/2e364cc6-726a-4850-a6f6-bd7dee5a4265)

</details>

Screen 2:

<details>

![image](https://github.com/phetsims/buoyancy/assets/6856943/21e1c567-5cd7-45ee-aff4-810e48e590f1)

</details>

Screen 3:

<details>

![image](https://github.com/phetsims/buoyancy/assets/6856943/b2ed8349-7091-4eb6-8b29-ca7a5c4f2f38)

</details>

Screen 4:

<details>


![image](https://github.com/phetsims/buoyancy/assets/6856943/487b66c3-7679-4f89-a6d9-544804781063)
</details>

**Comment by zepumph** [comment]
First step here is to add "supportsDynamicLocale" to the DBC package so we only use stringProperties.

**Comment by samreid** [comment]
I recommend https://github.com/phetsims/buoyancy/issues/133 be implemented before this issue, since it changes the layout/location of elements pertinent to this issue.

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
Alright. I believe that this is close to complete. The only item that I see left is this overlap in density text. Not sure what should be done about this.

<img width="925" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/74a3d972-3c5f-46cf-b6e5-5361c05dd3e6">


@AgustinVallejo, can you please recommend, and take a look at the other commits. Please poke around with stringTest=dynamic and see if you catch anything else that I missed. Thanks!

**Comment by AgustinVallejo** [comment]
Fixed, no more overlapping. Closing!

**Comment by zepumph** [comment]
I didn't see any notes about reviewing my code. Did you also take a look at dynamic locale generally in the sim suite as well as my  approach to solving it (mostly naive maxWidths?)

**Comment by AgustinVallejo** [comment]
Tested the sim with string tests and it looks really nice. Also the code looks fine as well. Closing
