### ISSUE TITLE
Support UI Sound

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#78]

**Comment by zepumph** [comment]
@DianaTavares and I discussed that we should also add pickup/drop sounds to the objects in the play area.

**Comment by AgustinVallejo** [comment]
Now supporting default UI sound. Will keep adding drag-drop sounds later (perfect opportunity to try out our RichDragListener)

I'll be looking at [this document](https://github.com/phetsims/tambo/blob/main/doc/adding-sound-to-a-sim.md) for referencing on the UI sound stuff

**Comment by AgustinVallejo** [comment]
Above commit adds default drag and drop. Marking for review and possibly closing

**Comment by AgustinVallejo** [comment]
Remember to add this in density as well!

**Comment by AgustinVallejo** [comment]
Closing as completed
