### ISSUE TITLE
Support Interactive Highlights

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#79]

**Comment by AgustinVallejo** [comment]
I think having this issue as well as https://github.com/phetsims/buoyancy/issues/76 is a little bit redundant. Will be closing this one and keeping an eye for interactive highlights in the other one. 

Also, the above commit pretty much enabled interactive highlights for mesh objects in the sim (with not super proper shapes), and the basic highlights for UI were turned on some days ago.
