### ISSUE TITLE
Inverted Cone texture is much darker than upwright cone

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#88]
Originally reported in https://github.com/phetsims/buoyancy/issues/43#issuecomment-1934812012. I can reproduce with most materials (not ice):

![image](https://github.com/phetsims/buoyancy/assets/6856943/03723331-9252-4fb5-a7a3-3bdc6e87d795)

**Comment by AgustinVallejo** [comment]
We discussed with DL today and decided to drop this. Modifying the light directions or intensity introduce visual changes to all sims in the suite, which is probably not worth a solution for this issue. Closing.
