### ISSUE TITLE
You can insert the cone into the inverted cone

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#89]
Originally reported in https://github.com/phetsims/buoyancy/issues/43#issuecomment-1934812012

![image](https://github.com/phetsims/buoyancy/assets/6856943/38de387c-fb27-477c-a29d-b24e7a9b13a4)

**Comment by zepumph** [comment]
As discussed in Design meeting today, we are going to defer this issue because the graphics model is sensitive and we should focus on publishing instead of making all interactions perfect (since it doesn't break anything). Deferring.

**Comment by samreid** [comment]
Based on the remark above, can this be closed as "will not fix"?

**Comment by samreid** [comment]
@DianaTavares @zepumph and I agreed to close the issue.
