### ISSUE TITLE
Unwanted buoyant force due to a thin layer of liquid inside of the boat

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/buoyancy#91]
In today's design meeting we noticed that, even when the boat is empty of liquids, it will produce a minor buoyant force on the block as follows (1.59N):

![image](https://github.com/phetsims/buoyancy/assets/37052186/c3168728-bda7-4c87-913e-c5e23960d857)

**Comment by zepumph** [comment]
I'm curious if it is about using a tolerance so that we never have a 0 volume in some case. Perhaps based on `DensityBuoyancyCommonConstants.TOLERANCE`. @AgustinVallejo can you take a look and let me know if you run into trouble?

**Comment by AgustinVallejo** [comment]
We're addressing this in here https://github.com/phetsims/buoyancy/issues/135
