### ISSUE TITLE
Draw the contact force of bodies when they are on top of each other.

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#93]
The simulation should display the contact force as is displayed in the next example: 

![image](https://github.com/phetsims/buoyancy/assets/26031501/3a69201e-8422-4890-96d7-58f14139786c)

The aluminum block is on top of the wood block, then the wood block have a contact force pointing down, equal to the aluminum weight, and the contact force up of that block is 132.3 (weight of the aluminum) + 18.6 (mass of the wood block) = 151.9 N.

the same happen with the boat. The boat need to show the contact force down and increase the one up when a block is inside it.

**Comment by zepumph** [comment]
I'm happy to take a first pass on this. I also think it would be an excellent issue to work on with @AgustinVallejo. I'll co-assign, but I'll also let you know if I get to it alone first.

**Comment by zepumph** [comment]
@AgustinVallejo and I took a look at this, and believe it will be prohibitively challenging to get the component contact forces out of the physics engine. The current way of doing things notes that the physics bodies only store a single value. 

https://github.com/phetsims/density-buoyancy-common/blob/16d076a81f76bf7c22675304e8070c3631ce580f/js/common/model/P2Engine.ts#L195-L197

So @AgustinVallejo and I recommend closing this as a "can't fix" :).

**Comment by DianaTavares** [comment]
Well, if it is super challenging, it is ok no to fix it. It is not related to the learning goals of the simulation, then it is ok. I will add to the teacher tips that the simulation is not to analyze forces generated by the ground like this:
![image](https://github.com/phetsims/buoyancy/assets/26031501/089563a9-19f8-4609-8969-2db43cbcb207)


But forces are ok in the pool (floating):
![image](https://github.com/phetsims/buoyancy/assets/26031501/efb52650-33b0-4f60-b0ef-ef8019685553)
