### ISSUE TITLE
Dynamic position of the forces diagram in the boat 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#94]
The force diagram of the boat is placed in the center:
![image](https://github.com/phetsims/buoyancy/assets/26031501/449afd90-c8c2-426a-ae5a-94f2667d7164)

When a block is inside the boat, that makes it hard to read the forces: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/a6d59dfe-ec5f-49ed-aebb-085c4aec4363)

The idea discussed in 8/feb/24 design meeting is to move the force diagram of the boat close to the tip (but that allow to read the mass) only when it is a block in the boat system (in the bottom of floating in the liquid inside the boat).

**Comment by AgustinVallejo** [comment]
Will work right now on this, but for the record, I worry that some teacher might complain that the forces are not being applied to the center of mass, as it is usually taught, and can even possibly imply some abnormal torque on the tip of the boat.

**Comment by AgustinVallejo** [comment]
Moved the force diagram some 75px to the left. Some things to decide in design meeting:
1. Again, are we okay with doing this? Complaints could arise from displaying the forces outside of the CoM.
2. Do we want to move them dynamically with boat size? i.e. at 70% of the boat's length. Or is the current default offset ok?
3. Is it worth it to investigate moving it only when the block is inside? DL and I feel this could be wrongly interpreted as a change in the position of the forces.

**Comment by zepumph** [comment]
Here is what this looks like right now: 

![image](https://github.com/phetsims/buoyancy/assets/6856943/96b980d6-2687-40b7-8347-12e1e58f11bf)

**Comment by zepumph** [comment]
Instead of hard coding a number that looks nice right now, can we make it dependent on the initial width of boat? Or based on the range of potential widths?

**Comment by zepumph** [comment]
We discussed this during design meeting and everyone liked the slight offset, and for it to remain static. @AgustinVallejo just the review comment above then.

**Comment by AgustinVallejo** [comment]
This is done, please give a double check and close @zepumph

**Comment by zepumph** [comment]
Looks like you added `mass.forceDiagramOffset`, but there is already a Property for that. Can we use that in the boat too? `mass.forceOffsetProperty`
