### ISSUE TITLE
Upthrust vs Buoyancy for UK users

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#95]
I created this issue not to forget to do the next steps once Buoyancy is published:

- [x] Utilize en_GB locale to change the word Buoyancy in the forces list to Upthrust
- [x] Write the teachers that suggested how to access to this change 
- [x] Add it to the teacher tips
- [ ] add it to the email that announce the buoyancy publication

**Comment by zepumph** [comment]
Buoyancy and Buoyancy basics 1.2.0 are now published. Marking off hold.

**Comment by DianaTavares** [comment]
I have done with this! It is not guaranteed that this month is going to be a newsletter, then I didn't check that bit I notify Sola to share the info in social media!
